# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand


# # Unit test for label_choiceset
# 
# context("label_choiceset")
# 
# test_that("label_choiceset returns the correct labels", {
#   dico <- list(variables = data.frame(name = c("x"),
#                                       list_name = "list"),
#                list = data.frame(name = c("a", "b"),
#                                  label = c("apple", "banana"),
#                                  list_name = "list"))
#   expect_equal(label_choiceset(dico, "x")("a"), "apple")
#   expect_equal(label_choiceset(dico, "x")("b"), "banana")
#   expect_equal(label_choiceset(dico, "x")("c"), "c")
# })

# test_that("label_choiceset works", {
# 
# })
