# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand


# Unit test for plot_integer function

# context("plot_integer function")
# 
# test_that("plot_integer function returns a plot", {
#   expect_true(is.ggplot(plot_integer(datalist = datalist, 
#                          dico = dico,
#                          var, 
#                          datasource = NULL,
#                          showcode = FALSE)))
# })
# 
# test_that("plot_integer function returns an invisible object when there is no recorded answer", {
#   expect_true(identical(invisible(plot_integer(datalist = datalist, 
#                          dico = dico,
#                          var, 
#                          datasource = NULL,
#                          showcode = FALSE)),invisible()))
# })
# test_that("plot_integer works", {
# 
# })
