# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand


# # Unit test
# context("plot_select_one_cross()")
# 
# test_that("plot_select_one_cross() produces a plot when all the arguments are provided", {
#   expect_true(!is.null(plot_select_one_cross(datalist = datalist,
#                             dico = dico,
#                             var = "age", 
#                             by_var = "gender",
#                             datasource = NULL,
#                             n = NULL,
#                             n_by = NULL,
#                             showcode = FALSE)))
# })

# test_that("plot_select_one_cross works", {
# 
# })
