# WARNING - Generated by {fusen} from dev/flat_dev.Rmd: do not edit by hand

# Unit test for kobo_frame()

# context("kobo_frame()")
# 
# test_that("kobo_frame() should return a data frame", {
#   expect_is(kobo_frame(datalist, dico, var), "data.frame") 
# })
# 
# test_that("kobo_frame() should contain the variable specified", {
#   expect_true(var %in% names(kobo_frame(datalist, dico, var)))
# })
# 
# test_that("kobo_frame() should contain an X_id column", {
#   expect_true("X_id" %in% names(kobo_frame(datalist, dico, var)))
# })

