# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand


# Unit test

# context("Test plot_select_one()")
# 
# test_that("plot_select_one() produces a plot object", {
#   expect_is(plot_select_one(datalist = NULL, dico = NULL, var = NULL), "gg")
# })
# 
# test_that("plot_select_one() requires three arguments", {
#   expect_error(plot_select_one(), "argument 'datalist' is missing")
#   expect_error(plot_select_one(datalist = NULL), "argument 'dico' is missing")
#   expect_error(plot_select_one(datalist = NULL, dico = NULL), "argument 'var' is missing")
# })


# test_that("plot_select_one works", {
# 
# })
