# WARNING - Generated by {fusen} from dev/flat_dev.Rmd: do not edit by hand


# ## Unit Test
# context("kobo_likert()")
# 
# test_that("kobo_likert() runs without errors", {
#   expect_error(kobo_likert())
# })
# 
# test_that("kobo_likert() returns the correct number of groups", {
#   expect_equal(nrow(grouplikert), kobo_likert())
# })
# 
# test_that("kobo_likert() plots the correct likert questions", {
#   expect_equal(plot_likert(datalist = datalist, 
#                       datasource = datasource,
#                       dico = dico,
#                       scopei =  scopei,
#                       repeatvari =  repeatvari,
#                       list_namei = list_namei,
#                       showcode = TRUE),
#               kobo_likert())
# })

# test_that("survey_label works", {
# 
# })
