# WARNING - Generated by {fusen} from dev/flat_dev.Rmd: do not edit by hand



# 
# # Unit test
# context("Testing the plot_select_multiple_cross function")
# 
# # Create a mock dataset
# datalist <- list(
#   data1 = list(
#     data1_var1 = c("A", "B", "C"),
#     data1_var2 = c("A", "B", NA)
#   ),
#   data2 = list(
#     data2_var1 = c("A", "B", "C"),
#     data2_var2 = c("A", "B", NA)
#   )
# )
# 
# # Create a mock dictionary
# dico <- list(
#   data1_var1 = list(
#     type = "select_multiple",
#     label = "Var1",
#     labelset = c("A", "B", "C")
#   ),
#   data1_var2 = list(
#     type = "select_one",
#     label = "Var2",
#     labelset = c("A", "B")
#   ),
#   form_title = "Data1"
# )
# 
# # Test that the function returns an invisible object when there is no intersection between the answers from the variables
# test_that("The function returns an invisible object when there is no intersection between the answers from the variables", {
#   expect_invisible(plot_select_multiple_cross(datalist = datalist, dico = dico, var = "data1_var1", by_var = "data1_var2"))
# })

# test_that("plot_select_multiple_cross works", {
# 
# })
