# WARNING - Generated by {fusen} from dev/flat_dev.Rmd: do not edit by hand



# # Unit test
# context("plot_select_multiple()")
# 
# test_that("plot_select_multiple() returns a ggplot object", {
#   expect_true(inherits(plot_select_multiple(datalist = datalist, dico = dico, var = "var1"), "gg"))
# })
# 
# test_that("plot_select_multiple() returns an invisible object when rr = 0", {
#   expect_true(invisible(plot_select_multiple(datalist = datalist, dico = dico, var = "var2")))
# })

# test_that("plot_select_multiple works", {
# 
# })
