# WARNING - Generated by {fusen} from dev/flat_dev.Rmd: do not edit by hand



# Unit test for kobo_ridl() using testthat
# 
# context("kobo_ridl()")
# 
# # Create mock objects to use in the test
# ridl <- "testRidl"
# datafolder <- "data"
# form <- "form.xlsx"
# namethisfile <- "testFile"
# visibility <- "public"
# stage <- "explo_initial"
# 
# # Create test for function
# test_that("kobo_ridl() creates the right resources", {
#   expect_true(kobo_ridl(ridl, datafolder, form, namethisfile, visibility, stage))
# })

# test_that("kobo_ridl works", {   expect_true(inherits(kobo_ridl, "function")) })
