# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand


# Unit Test: 

# context("Testing kobo_cruncher() function")
# 
# test_that("kobo_cruncher() produces the correct output", {
#   expect_equal(class(kobo_cruncher()), "list")
#   expect_equal(length(kobo_cruncher()), 5)
# })

# test_that("survey_label works", {
# 
# })
