# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

test_that("plot_header works", {
  
  dico <- kobo_dico( xlsformpath = system.file("sample_xlsform.xlsx", package = "kobocruncher") )
  check <- plot_header( dico = dico,   var = "profile")
  expect_true(inherits(plot_header, "function"))
  # expect_error(plot_header( dico = dico,   var = ""), " ")
  # expect_type(check, "list")
  # expect_identical(    check,  )
})
