# WARNING - Generated by {fusen} from dev/flat_dev.Rmd: do not edit by hand


# # Unit Test
# 
# test_that("label_varname() returns the correct label for a given variable name", {
#   # Create a test dictionary
#   dico <- list(variables = data_frame(name = c("var1", "var2"),
#                                       label = c("Variable 1", "Variable 2")))
#   
#   # Test that label_varname() returns the correct label
#   expect_equal(label_varname(dico, "var1"), "Variable 1")
#   expect_equal(label_varname(dico, "var2"), "Variable 2")
# })

# test_that("label_varname works", {
# 
# })
