# WARNING - Generated by {fusen} from dev/flat_dev.Rmd: do not edit by hand

# Unit Test

# context("plot_text()")
# 
# test_that("plot_text() returns a valid ggplot object", {
#   expect_is(plot_text(), "ggplot")
# })
# 
# test_that("plot_text() returns an empty plot when there is no text", {
#   expect_equal(plot_text(), ggplot2::ggplot() + ggplot2::theme_void())
# })
# test_that("plot_text works", {
# 
# })
