# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

# test_that("plot_select_one_cross works", {
# 
# })

# test_that("plot_select_multiple_cross works", {
# 
# })

# test_that("plot_integer_cros works", {
# 
# })

# test_that("plot_correlation works", {
# 
# })
