# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand


# # Unit Test
# context("label_varhint")
# test_that("label_varhint returns the correct hint for a given variable", {
#   dico <- list(variables = data.frame(name = c("x", "y"), hint = c("This is x", "This is y")))
#   expect_equal(label_varhint(dico, "x"), "This is x")
# })

# test_that("label_varhintworks", {
# 
# })
