# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' @title Shiny App - app_kobocruncher
#' 
#' @description  starts the graphical user interface developed with \emph{shiny}.
#' 
#' @param maxRequestSize (numeric) number defining the maximum allowed filesize (in megabytes)
#' for uploaded files, defaults to 50MB
#' @param debug logical if \code{TRUE}, set shiny-debugging options
#' @return starts the interactive graphical user interface 
#' @param theme select stylesheet for the interface. Supported choices are
#' \itemize{
#' \item 'yeti'
#' \item 'flatly'
#' \item 'journal'
#' \item 'IHSN'
#' }
#' @param ... arguments (e.g \code{host}) that are passed through \code{\link[shiny]{runApp}} when
#' starting the shiny application
#' @param shiny.server Setting this parameter to \code{TRUE} will return the app in the form of an 
#' object rather than invoking it. This is useful for deploying \code{app_kobocruncher} via \code{shiny-server}.
#' 
#' 
#' @importFrom shiny runApp shinyOptions
#' @export
#'


#' @examples
#' 
#' # app_kobocruncher(theme="flatly")
app_kobocruncher <- function(maxRequestSize=50, 
                        debug=FALSE, 
                        theme="IHSN", 
                        ..., 
                        shiny.server = FALSE) {
  if(!shiny.server)
    shiny::runApp(app_kobocruncher(maxRequestSize, debug, ggplot2::theme, ..., shiny.server = TRUE))
  
  if (!is.numeric(maxRequestSize)) {
    stop("argument 'maxRequestSize' must be numeric!\n")
  }
  
  if (maxRequestSize < 1) {
    maxRequestSize <- 10
  }
  
  appDir <- system.file("shiny", "kobocruncherApp", package="kobocruncher")
  
  if (appDir == "") {
    stop("Could not find example directory. Try re-installing `kobocruncher`.", call.=FALSE)
  }
  
  options(shiny.maxRequestSize=ceiling(maxRequestSize)*1024^2)
  options(shiny.fullstacktrace=debug)
  options(shiny.trace=debug)

  #.GlobalEnv$.startdir <- getwd()
  shiny::shinyOptions(.startdir = getwd())
  shiny::shinyOptions(.appDir = appDir)

  if (! theme %in% c("yeti","journal","flatly", "IHSN")) {
    stop("Invalid value for argument 'theme'\n")
  }

  if (theme=="yeti") {
    shiny::shinyOptions(.guitheme = "bootswatch_yeti.css")
    shiny::shinyOptions(.guijsfile = NULL)
  }

  if (theme=="journal") {
    shiny::shinyOptions(.guitheme = "bootswatch_journal.css")
    shiny::shinyOptions(.guijsfile = NULL)
  }
  if (theme=="flatly") {
    shiny::shinyOptions(.guitheme = "bootswatch_flatly.css")
    shiny::shinyOptions(.guijsfile = NULL)
  }

  if (theme=="IHSN") {
    shiny::shinyOptions(.guitheme = "ihsn-root.css")
    shiny::shinyOptions(.guijsfile = "js/ihsn-style.js")
  }
  
  source_from_appdir <- function(filename){
    source(file.path(appDir, filename), local = parent.frame(), chdir = TRUE)$value
  }
  
  shiny::shinyOptions(kobocruncherAppInvoked = TRUE)
  source_from_appdir("global.R")
  shiny::shinyOptions(kobocruncherAppInvoked = NULL)

  shiny::shinyApp(
    ui = source_from_appdir("ui.R"),
    server = source_from_appdir("server.R"),
    options = list(launch.browser=TRUE, ...)
  )
}

