# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' @title get the correct frame for one selected variable - important when havving variables within a repeat
#' @param datapath path to the file with the data format as extracted from kobo with dot as group separator and xml header
#' @param xlsformpath path to the xlsform file used to collect the data
#' @param var variable
#' @export

#' @examples
#' data <- kobo_frame(datapath = system.file("data.xlsx", package = "kobocruncher"),
#'                    xlsformpath = system.file("sample_xlsform.xlsx", package = "kobocruncher"),
#'                    var = "members.sex"   )
#' knitr::kable(head(data,5))
#'  
kobo_frame <- function(datapath,
                       xlsformpath, 
                       var) {
  
  datalist <- kobo_data(datapath )
  dico <-  kobo_dico(xlsformpath = xlsformpath)
  
  ## Identify the right frame number
  dataframen <- as.data.frame(dico[1]) |>
                  dplyr::filter(name == var) |>
                  dplyr::pull(dataframe)  
  ## Pull the data
  data  <-  datalist[dataframen] |>
              as.data.frame()
  
## get correct id whether the frmae is nested one or not.. 
if ("_id" %in% colnames(data)) { data$X_id <-  data$`_id` } else {  }
if ("_index" %in% colnames(data)) { data$X_id <-  data$`_index` } else {  }
if ("X_index" %in% colnames(data)) { data$X_id <-  data$X_index  } else { }
if ("X_id" %in% colnames(data)) { data$X_id <-  row.names(data)  } else { }
  
  ## Make sure the data actually contain the variable if not put to null
 if ( var %in% names(data)) {
   data <- data
 }  else {
   data <- data.frame( type = character())
   names(data)[1] <- var  
  
 }
    
    return(data )
}

