# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' @title get the correct frame for one selected variable - important when having variables within a repeat
#' @param datalist An object of the "datalist" class as defined in kobocruncher 
#' @param dico An object of the "kobodico" class format as defined in kobocruncher
#' @param var variable
#' @export

#' @examples
#' dico <- kobo_dico( xlsformpath = system.file("sample_xlsform.xlsx", package = "kobocruncher") )
#' datalist <- kobo_data(datapath = system.file("data.xlsx", package = "kobocruncher") )
#' 
#' data <- kobo_frame(datalist = datalist,
#'                    dico = dico,
#'                    var = "members.sex"   )
#' knitr::kable(utils::head(data,5))
#'  
kobo_frame <- function(datalist,
                       dico, 
                       var) {
  
  ## Identify the right frame number
  dataframen <- as.data.frame(dico[["variables"]]) |>
                  dplyr::filter(name == var) |>
                  dplyr::pull(repeatvar)  
  ## Pull the data
  data  <-  datalist[[dataframen]] |>
              as.data.frame()
  
## get correct id whether the frame is nested one or not.. 
if ("_id" %in% colnames(data)) { data$X_id <-  data$`_id` } else {  }
if ("_index" %in% colnames(data)) { data$X_id <-  data$`_index` } else {  }
if ("X_index" %in% colnames(data)) { data$X_id <-  data$X_index  } else { }
if ("X_id" %in% colnames(data)) { data$X_id <-  row.names(data)  } else { }
  
  ## Make sure the data actually contain the variable if not put to null
 if ( var %in% names(data)) {
   data <- data
 }  else {
   data <- data.frame( type = character())
   names(data)[1] <- var  
  
 }
    
    return(data )
}

