# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' @title Crunch all variables according to the analysis plan 
#' 
#' @param datalist An object of the "datalist" class as defined in kobocruncher 
#' @param dico path to the xlsform file used to colllect the data
#' @param datasource name of the data source to display, if set to NULL - then pulls the form_title within the settings of the xlsform 
#' @export
 
#' @examples
#' dicolikert <- kobo_dico( xlsformpath = system.file("form_likert.xlsx", package = "kobocruncher") )
#' datalistlikert <- kobo_data(datapath = system.file("data_likert.xlsx", package = "kobocruncher") )
#' 
#' kobo_likert(datalist = datalistlikert,
#'               dico = dicolikert,
#'               datasource = "a great survey!")
#' 
#' 
kobo_likert <- function(datalist = datalist, 
                          datasource = NULL,
                          dico = dico) {
  
  ## Get default data source name 
  if( is.null(datasource)) {datasource <- as.character(  dico[3][[1]]$form_title ) }
  
  require(dplyr)
  ## Check the frequency of list_name within each group,
  ## Filter the combination of list and group where we have more than 3 occurrences
  # not taking in account when the appearance is not "label"
  grouplikert <- as.data.frame(dico[1]) |>
    dplyr::filter( type ==  "select_one") |>
    dplyr::filter( appearance !=  "label") |>
    dplyr::group_by( scope, list_name, dataframe) |>
    dplyr::summarise( cnt= dplyr::n() )|>
    dplyr::filter( cnt >= 2)
  
  if(nrow(grouplikert)  == 0) {
    cat("No potential likert in the form")
    } else {
          for (i in 1:nrow(grouplikert)  ) {
          ## getting the group and corresponding label
          scopei <-   as.character(grouplikert[i, c("scope")])
          dataframei <-   as.character(grouplikert[i, c("dataframe")])
          ## geting the list_name and corresponding label
          list_namei <- as.character( grouplikert[i, c("list_name")])
          
          p <- plot_likert(datalist = datalist, 
                      datasource = datasource,
                      dico = dico,
                      scopei =  scopei,
                      dataframei =  dataframei,
                      list_namei = list_namei,
                      showcode = TRUE)
          return(p)
  
        }
    }
}

