# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' @title Crunch a variable
#' @param datapath path to the file with the data format as extracted from kobo with dot as group separator and xml header
#' @param xlsformpath path to the xlsform file used to colllect the data
#' @param type type of the variable to display
#' @param name name of the variable to display
#' @param disaggregation vector with the potential variables to use for cross tabulation
#' @param correlate vector with the potential variables to use for testing statistical association
#' @param showcode display the code
#' @export
 
#' @examples
#' kobo_cruncher(datapath = system.file("data.xlsx", package = "kobocruncher"),
#'               xlsformpath =  system.file("sample_xlsform.xlsx", package = "kobocruncher"), 
#'               type = "select_one", 
#'               name = "profile.country",
#'               showcode = TRUE)
kobo_cruncher <- function(datapath = datapath, 
                          xlsformpath = xlsformpath,
                          type, 
                          name, 
                          disaggregation = "", 
                          correlate = "", 
                          showcode = TRUE) {
  
  if (type == "begin_group") output_header(xlsformpath = xlsformpath, 
                                           var = name)
  
  else if (type == "select_one") plot_select_one(datapath = datapath, 
                                                 xlsformpath = xlsformpath,
                                                 var = name, 
                                                 showcode = TRUE)
  else if (type == "select_multiple") plot_select_multiple(datapath = datapath,
                                                           xlsformpath = xlsformpath, 
                                                           var = name, 
                                                           showcode = TRUE)
  else if (type %in% c("numeric", "integer")) plot_integer(datapath = datapath, 
                                           xlsformpath = xlsformpath,
                                           var = name, 
                                           showcode = TRUE)
  else if (type == "text") plot_text(datapath = datapath, 
                                     xlsformpath = xlsformpath, 
                                     var = name, 
                                     showcode = TRUE)
}

