# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' Apply cleaning based on date and interview duration
#' 
#' Use metadata end & stat to apply automatic cleaning. 
#' The functions removes not only the 
#' main table but also the nested one
#' 

#' @param datalist An object of the "datalist" class as defined in kobocruncher 
#' @param startdatacollectiondate date when data collection started
#' @param enddatacollectiondate date when data collection ended
#' @param standardeviation number in minutes defining the accepted standard 
#'         deviation for the duration of the interview - for instance + or - 20 minutes
#' 
#' 
#' @return datalist An object of the "datalist" class as defined in kobocruncher
#' 
#' @export
#' @examples
#' # datalist <- kobo_data(datapath = system.file("data.xlsx", package = "kobocruncher") )
#' # nrow(datalist[[1]])
#' # datalist <- kobo_clean_time(datalist,
#' #                             startdatacollectiondate = "2022-10-25",
#' #                             enddatacollectiondate = "2022-10-29",
#' #                             standardeviation = 25)
#' # nrow(datalist[[1]])
# kobo_clean_time <- function(datalist, 
#                             startdatacollectiondate,
#                             enddatacollectiondate,
#                             standardeviation){
#     
#     ## Open the master frame and perform the calculation and filters
#     ds <- datalist[[1]]  |>
#           ## reformat data
#           dplyr::mutate( start = dplyr::if_else(nchar(start) == 29,
#                                 substr(start,0,23) ,
#                                 start)) |>
#           dplyr::mutate( start = stringi::stri_datetime_format(strptime(start ,
#                                       "%Y-%m-%dT%H:%M:%OS"))) |>
#       
#       
#           dplyr::mutate( end = dplyr::if_else(nchar(end) == 29,
#                                 substr(end,0,23) ,
#                                 end)) |>
#           dplyr::mutate( end = stringi::stri_datetime_format(strptime(end ,
#                                       "%Y-%m-%dT%H:%M:%OS"))) |>
#           dplyr::mutate( duration = difftime(end, 
#                                         start,  
#                                         units = "secs") / 60) |>
#           ## Apply filter on start and end data collection date
#           dplyr::filter( as.Date(start) > as.Date(startdatacollectiondate))|>
#           dplyr::filter( as.Date(start) < as.Date(enddatacollectiondate)) 
#     
#     ### Get values for Average and Standard Deviation for the interview duration 
# 
#     ## Now remove all orphans records from nested frame
#     
#     
#         
#         
# 
#   return(datalist)
#   
#     
# }
