# WARNING - Generated by {fusen} from dev/flat_dev.Rmd: do not edit by hand

#' @title Crunch all variables according to the analysis plan 
#' 
#' @param datalist An object of the "datalist" class as defined in kobocruncher 
#' @param dico path to the xlsform file used to collect the data
#' @param datasource name of the data source to display, if set to NULL - then pulls the form_title within the settings of the xlsfor
#' @param n if not NULL, lumps all levels except for the n most frequent (or least frequent if n < 0) - cf
#'            forcats::fct_lump_n()
#' @param n_by if not NULL, lumps all levels for the cross tabulation variable except for the n_by most frequent (or least frequent if n < 0) - cf
#'            forcats::fct_lump_n()
#' @export
#' @examples
#' dico <- kobo_dico( xlsformpath = system.file("sample_xlsform.xlsx", package = "kobocruncher") )
#' datalist <- kobo_data(datapath = system.file("data.xlsx", package = "kobocruncher") )
#'
#' kobo_cruncher(datalist = datalist,
#'               dico = dico,
#'               datasource = "a great survey!")
#'
#'

# prefixer::import_from(fun = kobo_cruncher)


 
kobo_cruncher <- function(datalist = datalist, 
                          datasource = NULL,
                          dico = dico,
                          n = 5,
                          n_by = 5) {
  
  ## Get default data source name 
  if( is.null(datasource)) {datasource <- as.character(  dico[[3]]$form_title ) }
  
  questions <- as.data.frame(dico[[4]])
  disaggregation <-  c(as.data.frame(dico[["variables"]]) |> 
                        dplyr::filter( !(is.na(disaggregation))) |>
                        dplyr::pull(name) )
  
  correlate <-   c(as.data.frame(dico[["variables"]]) |> 
                   dplyr::filter( !(is.na(correlate))) |>
                   dplyr::pull(name))
  
  
  ## If disaggregation not included in the function argument then use what's set up in the analysis plan
  if (  length(disaggregation) == 1 ) { 
    if (  disaggregation == "" ) { 
      disaggregation <- as.data.frame(dico[["variables"]]) |> 
        dplyr::filter( !(is.na(disaggregation))) |>
        dplyr::pull(name) } }
  

  # If correlate not included in the function argument then use what's set up in the analysis plan
  if (length(correlate) ==1) {
    if (correlate == "") { correlate <- as.data.frame(dico[["variables"]])|> 
      dplyr::filter( !(is.na(correlate))) |>
      dplyr::pull(name) }}
  
  ## Looping around the questions as set up in the report plan ###
  for ( i in 1:nrow(questions)) {
      type <-  questions[ i, c("type")]
      name <- questions[ i, c("name")]
      
      if (type == "begin_group") { cat(plot_header(dico = dico,
                                               var = name)) }
      
      ## Univariate analysis ######
      if (type == "select_one") print(plot_select_one(datalist = datalist, 
                                                dico = dico,
                                                var = name,  
                                                datasource = datasource,
                                                n = n,
                                                showcode = TRUE))
      
      if (type == "select_multiple") print(plot_select_multiple(datalist = datalist,
                                                          dico = dico, 
                                                          var = name,  
                                                          datasource = datasource,
                                                          n = n,
                                                          showcode = TRUE))
      
      if (type %in% c("numeric", "integer", "range", "calculate")) print(plot_integer(datalist = datalist, 
                                                          dico = dico,
                                                          var = name,  
                                                          datasource = datasource,
                                                          showcode = TRUE))
      
      if (type == "text") print(plot_text(datalist = datalist, 
                                    dico = dico, 
                                    var = name,  
                                    datasource = datasource,
                                    showcode = TRUE))
      
    
       ## Bivariate analysis #####
      if (type == "select_one" &  length(disaggregation)>=1 ) {
        for (disag in disaggregation  ){
          if(disag  != "")
            print(plot_select_one_cross(datalist = datalist, 
                                  dico = dico,
                                  var = name, 
                                  by_var = disag, 
                                  datasource = datasource,
                                  n = n,
                                  n_by = n_by,
                                  showcode = TRUE)) }
      }
      if (type == "select_multiple" &  length(disaggregation)>=1 ) {
        for (disag in disaggregation  ){
          if(disag  != "")
            print(plot_select_multiple_cross(datalist = datalist, 
                                  dico = dico,
                                  var = name, 
                                  by_var = disag,
                                  datasource = datasource,
                                  n = n,
                                  n_by = n_by,
                                  showcode = TRUE)) }
      }
      if (type %in% c("numeric", "integer", "range", "calculate") &  length(disaggregation)>=1 ) {
        for (disag in disaggregation  ){
          
          if(disag  != "")
            print(plot_integer_cross(datalist = datalist, 
                               dico = dico,
                               var = name, 
                               by_var = disag, 
                               datasource = datasource,
                               showcode = TRUE)) }
      }
    
    ## Statistical Association  #
      if (type == "select_one" &  length(correlate)>=1 ) {
        for (correl in correlate  ){
          
          if(correl  != "")
            print(plot_correlation(datalist = datalist, 
                             dico = dico,
                             var = name, 
                             by_var = correl,
                             datasource = datasource,
                             showcode = TRUE)) }
      }
  
  }
}




