# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' @title Data loading
#' @param datapath path to the file with the data format as extracted from kobo with dot as group separator and xml header
#' 
#' @return A "datalist" S3 class object (list) formatted to the specifications of "kobocruncher".
#'  
#' @export
#' @importFrom readxl excel_sheets read_excel
# prefixer::import_from(fun = kobo_data)
  
#' @examples
#' datalist <- kobo_data(datapath = system.file("data.xlsx", package = "kobocruncher") )
#' # MainFrame
#' datalist[["main"]]
#' # Second Frame - based on presence of repeat within the form, aka nested or
#' # hierarchical data structure, etc... 
#' datalist[["members"]]
kobo_data <- function(datapath) {
   # cat(readxl::excel_sheets(datapath ))
  
  datalist <- lapply(readxl::excel_sheets(datapath ), function(x) readxl::read_excel(datapath , sheet = x))  
  
  # Get sheet names
  sheet_names <- readxl::excel_sheets(datapath)  
  ## rename the first sheet as name
  sheet_names[1] <- "main"
  # Rename list elements
  names(datalist) <- sheet_names  
    
    ## In case we do not have the right group separator!
    datalist <- lapply(datalist, function(y) {colnames(y) <- gsub("/", ".", colnames(y)); y})
    
     
    #names(datalist) <- readxl::excel_sheets(datapath )
    
   ## Rebuild  a single key var - parent_index between the main frames and nested ones.. assume a single level of nesting
    datalist[[1]]$parent_index <- datalist[[1]]$'_index'  
    if (length(datalist) >1 ) {
        for (m in 2:length(datalist)) {
        datalist[[m]]$parent_index <- datalist[[m]]$'_parent_index'    }
    }
    class(datalist) <- "datalist" # assigns a "datalist" class to the list. Helpful for later on.
    return(datalist)
}


