# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' @title Crunch all variables according to the analysis plan 
#' 
#' @param datalist An object of the "datalist" class as defined in kobocruncher 
#' @param dico path to the xlsform file used to colllect the data
#' @export
 
#' @examples
#' dico <- kobo_dico( xlsformpath = system.file("sample_xlsform.xlsx", package = "kobocruncher") )
#' datalist <- kobo_data(datapath = system.file("data.xlsx", package = "kobocruncher") )
#' 
#' kobo_cruncher(datalist = datalist,
#'               dico = dico)
#' 
#' 
kobo_cruncher <- function(datalist = datalist, 
                          dico = dico) {
  
  
  questions <- as.data.frame(dico[4])
  disaggregation <-  c(as.data.frame(dico[1]) |> 
                        dplyr::filter( !(is.na(disaggregation))) |>
                        dplyr::pull(name) )
  
  correlate <-   c(as.data.frame(dico[1]) |> 
                   dplyr::filter( !(is.na(correlate))) |>
                   dplyr::pull(name))
  
  
  ## If disaggregation not included in the function argument then use what's set up in the analysis plan
  if (  length(disaggregation) == 1 ) { 
    if (  disaggregation == "" ) { 
      disaggregation <- as.data.frame(dico[1]) |> 
        dplyr::filter( !(is.na(disaggregation))) |>
        dplyr::pull(name) } }
  

  # If correlate not included in the function argument then use what's set up in the analysis plan
  if (length(correlate) ==1) {
    if (correlate == "") { correlate <- as.data.frame(dico[1])|> 
      dplyr::filter( !(is.na(correlate))) |>
      dplyr::pull(name) }}
  
  ## Looping around the questions as set up in the report plan ###
  for ( i in 1:nrow(questions)) {
      type <-  questions[ i, c("type")]
      name <- questions[ i, c("name")]
      
      ## Univariate analysis ######
      if (type == "begin_group") plot_header(dico = dico, 
                                               var = name)
      
      if (type == "select_one") plot_select_one(datalist = datalist, 
                                                dico = dico,
                                                var = name, 
                                                showcode = TRUE)
      
      if (type == "select_multiple") plot_select_multiple(datalist = datalist,
                                                          dico = dico, 
                                                          var = name, 
                                                          showcode = TRUE)
      
      if (type %in% c("numeric", "integer")) plot_integer(datalist = datalist, 
                                                          dico = dico,
                                                          var = name, 
                                                          showcode = TRUE)
      
      if (type == "text") plot_text(datalist = datalist, 
                                    dico = dico, 
                                    var = name, 
                                    showcode = TRUE)
      
    
       ## Bivariate analysis #####
      if (type == "select_one" &  length(disaggregation)>=1 ) {
        for (disag in disaggregation  ){
          if(disag  != "")
            plot_select_one_cross(datalist = datalist, 
                                  dico = dico,
                                  var = name, 
                                  by_var = disag,
                                  showcode = TRUE) }
      }
      if (type == "select_multiple" &  length(disaggregation)>=1 ) {
        for (disag in disaggregation  ){
          if(disag  != "")
            plot_select_multiple_cross(datalist = datalist, 
                                  dico = dico,
                                  var = name, 
                                  by_var = disag,
                                  showcode = TRUE) }
      }
      if (type %in% c("numeric", "integer") &  length(disaggregation)>=1 ) {
        for (disag in disaggregation  ){
          
          if(disag  != "")
            plot_integer_cross(datalist = datalist, 
                               dico = dico,
                               var = name, 
                               by_var = disag,
                               showcode = TRUE) }
      }
    
    ## Statistical Association  #
      if (type == "select_one" &  length(correlate)>=1 ) {
        for (correl in correlate  ){
          
          if(correl  != "")
            plot_correlation(datalist = datalist, 
                             dico = dico,
                             var = name, 
                             by_var = correl,
                             showcode = TRUE) }
      }
  
  }
}

