# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' @title Get all the choices labels options for a specific variable
#' @param xlsformpath path to the xlsform file used to cole
#' @param x variable
#' @export

#' @examples
#' label_choiceset(xlsformpath =  system.file("sample_xlsform.xlsx", package = "koboloadeR"), 
#'                 x="profile.country")
label_choiceset <- function(xlsformpath,
                            x) {
  dico <-  kobo_dico(xlsformpath = xlsformpath)
  lname <- as.data.frame(dico[1]) |>
    dplyr::filter(name == x) |>
    dplyr::pull(list_name)
  
 as.data.frame(dico[2]) |>
    dplyr::filter(list_name == lname)
}

