# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' @title Get Interpretation hint for a specific variable
#' @param xlsformpath path to the xlsform file used to cole
#' @param x variable
#' @export

#' @examples
#' label_varhint(xlsformpath = system.file("sample_xlsform.xlsx", package = "kobocruncher"), 
#'               x ="profile.country")
label_varhint <- function(xlsformpath, x) {
  dico <-  kobo_dico(xlsformpath = xlsformpath)
  as.data.frame(dico[1]) |>
    dplyr::filter(name == x) |>
    dplyr::pull(hint)
}

