# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' @title Get all the choices labels options for a specific variable if available
#' 
#' @description This labeling function ia function factory - https://adv-r.hadley.nz/function-factories.html
#' The output of this function is actually a function
#' @param dico An object of the "kobodico" class format as defined in kobocruncher
#' @param x variable
#' @export

# prefixer::import_from(fun = kobo_dico)


#' @examples
#' dico <- kobo_dico( xlsformpath = system.file("sample_xlsform.xlsx", package = "kobocruncher") )
#' datalist <- kobo_data(datapath = system.file("data.xlsx", package = "kobocruncher") )
#' 
#' data <- kobo_frame(datalist = datalist,
#'                    dico = dico,
#'                    var = "profile.country"   )
#' 
#' label_choiceset(dico = dico, 
#'                 x="profile.country")(data$profile.country)
#' 
#' ## Test when there's no dictionnary
#' data$profile.occupation
#' label_choiceset(dico = dico, 
#'                 x="profile.occupation")(data$profile.occupation)
#' 
#' 
#' label_choiceset(dico = dico, 
#'                 x="profile.occupation")(data$profile.occupation)
#' 
label_choiceset <- function(dico,
                            x) {
  lname <- as.data.frame(dico[["variables"]]) |>
    dplyr::filter(name == x) |>
    dplyr::pull(list_name)
  
  dict <- 
    as.data.frame(dico[[2]]) |>
    dplyr::filter(list_name == lname) |> 
    (\(x) purrr::set_names(x$label, x$name))()
  
#  function(y) { dict[y] |> tidyr::replace_na("Other") }
 # function(y) { dplyr::if_else(is.na(dict[y]), y, dict[y]) }
  function(y) { ifelse(is.na(dict[y]), y, dict[y]) }

}



