# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' @title Get the label for a specific choice if available
#' @param xlsformpath path to the xlsform file used to cole
#' @param x character with the code for the choice
#' @export

#' @examples
#' label_choice(xlsformpath =  system.file("sample_xlsform.xlsx", package = "koboloadeR"), 
#'               x = "profile.country")
#' 
label_choice <- function(xlsformpath, x ) {
   label_choiceset(xlsformpath = xlsformpath, x) %>%
            ## Need to address situation where dictionary is empty
           ## in this case we leave data as is...
          dplyr::mutate( label = dplyr::if_else(is.na(label),name, label) ) %>%
          
          # create a named character object to relabel
          { purrr::set_names(.$label, .$name) } 

}

