# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' @title Get the label for a specific variable
#' @param xlsformpath path to the xlsform file used to collect the data
#' @param x character with the variable name
#' @export

#' @examples
#' 
#' label_varname(xlsformpath = system.file("sample_xlsform.xlsx", package = "koboloadeR"), 
#'               x ="profile.country")
#' 
label_varname <- function(xlsformpath, x) {
  dico <-  kobo_dico(xlsformpath = xlsformpath)
  as.data.frame( dico[1]) |>
    dplyr::filter(name == x) |>
    dplyr::pull(label)
}

