# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' @title Get the label for a specific variable
#' @param dico An object of the "kobodico" class format as defined in kobocruncher
#' @param x character with the variable name
#' @export

#' @examples
#' dico <- kobo_dico( xlsformpath = system.file("sample_xlsform.xlsx", package = "kobocruncher") )
#' 
#' label_varname(dico = dico, 
#'               x ="profile.country")
#' 
label_varname <- function(dico, x) {
  as.data.frame( dico[1]) |>
    dplyr::filter(name == x) |>
    dplyr::pull(label)
}

