# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' @title Get all the choices labels options for a specific variable if available
#' 
#' @description This labeling function ia function factory - https://adv-r.hadley.nz/function-factories.html
#' The output of this function is actually a function
#' @param xlsformpath path to the xlsform file used to cole
#' @param x variable
#' @export

#' @examples
#' data <- kobo_frame(datapath = system.file("data.xlsx", package = "kobocruncher"),
#'                    xlsformpath = system.file("sample_xlsform.xlsx", package = "kobocruncher"),
#'                    var = "profile.country"   )
#' label_choiceset(xlsformpath =  system.file("sample_xlsform.xlsx", package = "kobocruncher"), 
#'                 x="profile.country")(data$profile.country)
#' 
#' ## Test when there's no dictionnary
#' data$profile.occupation
#' label_choiceset(xlsformpath =  system.file("sample_xlsform.xlsx", package = "kobocruncher"), 
#'                 x="profile.occupation")(data$profile.occupation)
label_choiceset <- function(xlsformpath,
                            x) {
  dico <-  kobo_dico(xlsformpath = xlsformpath)
  lname <- as.data.frame(dico[1]) |>
    dplyr::filter(name == x) |>
    dplyr::pull(list_name)
  
  dict <- 
    as.data.frame(dico[2]) |>
    dplyr::filter(list_name == lname) |> 
    (\(x) purrr::set_names(x$label, x$name))()
  
#  function(y) { dict[y] |> tidyr::replace_na("Other") }
  function(y) { dplyr::if_else(is.na(dict[y]), y, dict[y]) }

}

