# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' @title Plotting Correlation
#' @param datapath path to the file with the data format as extracted from kobo with dot as group separator and xml header
#' @param xlsformpath path to the xlsform file used to cole
#' @param var name of the variable to display
#' @param showcode display the code
#' @export

#' @examples
#' plo_correlation(datapath = system.file("data.xlsx", package = "kobocruncher"),
#'               xlsformpath =  system.file("sample_xlsform.xlsx", package = "kobocruncher"), 
#'               var = "profile.occupation")
plo_correlation <- function(datapath = datapath, 
                      xlsformpath = xlsformpath,
                      var, 
                      showcode = FALSE) {
  
 
}

