# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' @title Plotting Select multiple variable
#' @description
#' Note that if the column order is set in the xlsform choice part, the variable will be de factor considered as ordinal and the default ordering will not be done based on frequency
#' @param datalist An object of the "datalist" class as defined in kobocruncher 
#' @param dico An object of the "kobodico" class format as defined in kobocruncher
#' @param var name of the variable to display
#' @param datasource name of the data source to display, if set to NULL - then pulls the form_title within the settings of the xlsform 
#' @param showcode display the code
#' 
#' @importFrom ggplot2 aes  geom_col geom_label scale_x_continuous scale_y_discrete coord_cartesian labs theme_minimal geom_vline theme element_line element_blank
#' @importFrom data.table :=  
#' @export

#' @examples
#' dico <- kobo_dico( xlsformpath = system.file("sample_xlsform.xlsx", package = "kobocruncher") )
#' datalist <- kobo_data(datapath = system.file("data.xlsx", package = "kobocruncher") )
#' 
#' 
#' plot_select_multiple(datalist = datalist,
#'               dico = dico, 
#'               var = "profile.reason",
#'               showcode = TRUE
#'             )
#' 
#' # plot_select_multiple(datalist = datalist,
#' #               dico = dico, 
#' #               var = "profile.reason1",
#' #               showcode = TRUE
#' #             )
#' 
plot_select_multiple <- function(datalist = datalist, 
                                 dico = dico,
                                 var, 
                                 datasource = NULL,
                                 showcode = FALSE) {
  
  requireNamespace("ggplot2")
  requireNamespace("dplyr")
  
  ## Get default data source name 
  if( is.null(datasource)) {datasource <- as.character(  dico[[3]]$form_title ) }
  
  data <- kobo_frame(datalist = datalist,
                   dico = dico,
                   var = var  )
  
  ## get response rate: rr
  rr <- mean(!is.na(data[[var]]))
  nr <- sum(!is.na(data[[var]]))

  
  if ( is.nan(rr)) {
    cat(paste0("<strong style=\"color:#0072BC;\">The variable from the form called: ",var," could not be identified in the dataset</strong>\n\n"))
    #return(invisible(NULL))
      return(invisible())
    
  } else {
  
  ## If not empty
  if (rr != 0 & ! (is.nan(rr)) ) {    
  
  cnts <- data |>
    tidyr::drop_na(tidyselect::all_of(var)) |>
    tidyr::separate_rows(.data[[var]], sep = " ") |>
    ## Check if we have _id -  
    
    # Lump together factor levels into "other"
    dplyr::distinct(`X_id`, !!var := forcats::fct_lump_n(factor(.data[[var]]), n = 5)) |>
    dplyr::count(x := .data[[var]]) |>
    dplyr::mutate(p = n/nr)
  
  ## Manage situation if ordinal variable (i.e. order is set in choices)
  if (any(!is.na(dplyr::filter(dico[[2]], list_name == var)$order))) {
    
    ## case there are duplicated answers options - for instance if allow_choice_duplicates = yes
    ll <- dplyr::filter(dico[[2]], list_name == listvar) |>
          dplyr::group_by(name) |> 
          dplyr::slice_head(n = 1)
    
    cnts <- cnts |>
      dplyr::left_join( dplyr::filter(ll), by = c("x"="name"))|>
      dplyr::mutate(x = forcats::fct_reorder(x, order, as.numeric))
  } else {
    cnts <- cnts |>
      dplyr::mutate(x = forcats::fct_reorder(x, n))
  }

    
    ## Writing code instruction in report
    if( showcode == TRUE) {
      cat(paste0(label_varname(dico = dico,
                                                   x = var), "\n",
                                      "  `plot_select_multiple(datalist = datalist, dico = dico, \"", var, "\")` \n\n "))}   else {} 
    
    require(ggplot2)
    ## Plot
     p <- ggplot2::ggplot(cnts, aes(p, x)) +
      geom_col(fill = "#0072BC") +
      #geom_label(aes(label = scales::label_percent(accuracy = .01)(p))) + 
      ## Position label differently in the bar in white - outside bar in black
      geom_label( data =   function(x) subset(x, p < max(p) / 1.5),
                    aes(label = scales::label_percent(accuracy = .01)(p)),
                    hjust = -0.1 ,
                    vjust = 0.5, 
                    colour = "black", 
                    fill = NA, 
                    label.size = NA, 
                    size = 6   ) +  
      geom_label( data =   function(x) subset(x, p >= max(p) / 1.5),
                    aes(label = scales::label_percent(accuracy = .01)(p)),
                    hjust = 1.1 ,
                    vjust = 0.5, 
                    colour = "white", 
                    fill = NA, 
                    label.size = NA,
                    size = 6   ) +   
      
      scale_x_continuous(labels = scales::label_percent()) +
      scale_y_discrete(labels = function(x) {label_choiceset(dico = dico,
                                                        x = var)(x) |>
          stringr::str_wrap(40)}) +
      coord_cartesian(clip = "off") +
      labs(x = NULL, y = NULL,
           title = stringr::str_wrap(label_varname(dico = dico, x= var), 90),
           subtitle = if (!is.na(label_varhint(dico = dico, x = var))){ 
                     stringr::str_wrap(label_varhint(dico = dico, x = var), 90)} else { ""},
           caption = glue::glue("Multiple choice question, Response rate = {scales::label_percent(accuracy = .01)(rr)} on a total of {nrow(data)} records \n Source: {datasource}")) +
      theme_minimal( base_size = 24) + 
      geom_vline(xintercept = 0, size = 1.1, colour = "#333333") +
      theme( panel.grid.major.x  = element_line(color = "#cbcbcb"), 
             panel.grid.major.y  = element_blank(), 
             panel.grid.minor = element_blank()    ) +
      theme(plot.title.position = "plot")
     
     
   return(p) #  print(p)
    
    #plot_select_multiple_cross(var,   by_var)
    
  } else { 
    cat(paste0("<strong style=\"color:#0072BC;\"> No recorded answers for the question: </strong>",var,"\n\n")) 
      return(invisible())
    #return(invisible(NULL))
    }
  # cat("\n\n")
    
  }  
}

