# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' @title Plotting Likert
#' 
#' @description Detect if we have more than 3 questions with the same response options within the same questions group
#' and represent the result using a standard likert plot - build from  https://github.com/jbryer/likert
#' 
#' @param datalist An object of the "datalist" class as defined in kobocruncher 
#' @param dico An object of the "kobodico" class format as defined in kobocruncher
#' @param scopei group in which the likert frame are
#' @param list_namei name of the likert option list
#' @param repeatvari name of the frame within the dataset where to look for the data
#' @param datasource name of the data source to display, if set to NULL - then pulls the form_title within the settings of the xlsform 
#' @param showcode display the code
#' 
#' @importFrom stats setNames
#' @importFrom dplyr if_any everything mutate_all funs 
#' @importFrom ggplot2 labs theme_minimal theme margin
#' @importFrom likert likert
#' 
#' @export

# prefixer::import_from(fun = plot_likert)



#' @examples
#' dicolikert <- kobo_dico( xlsformpath = system.file("form_likert.xlsx", package = "kobocruncher") )
#' datalistlikert <- kobo_data(datapath = system.file("data_likert.xlsx", package = "kobocruncher") )
#' 
#' plot_likert(datalist = datalistlikert,
#'             dico = dicolikert,
#'             datasource = NULL,
#'             scopei =  "group_ei8jz33",
#'             repeatvari =   "main",
#'             ## getting the list_name and corresponding label
#'             list_namei = "yk0td68" 
#'           )
plot_likert <- function(datalist = datalist,
                        dico = dico,
                        scopei,
                        list_namei,
                        repeatvari,
                        datasource = NULL,
                        showcode = FALSE) {
 
   ## Get default data source name 
  if( is.null(datasource)) {datasource <- as.character(  dico[[3]]$form_title ) }
  require(dplyr)
  require(ggplot2)
  require(likert)
  require(cowplot)
  
   ## Writing code instruction in report
    if( showcode == TRUE) {
      cat(paste0( 
   "`plot_likert(datalist, dico, scopei=\"",scopei, "\", list_namei=\"", list_namei, "\", repeatvari=\"", repeatvari, "\",datasource=params$datasource)` \n\n "))} else {}
             
   labelgroup <- as.data.frame(dico[["variables"]]) |>
            dplyr::filter( name  %in%  c(scopei)) |>
            dplyr::select( label) |>
            dplyr::pull()
          
    nlevel_likert <- as.data.frame(dico[[2]]) |>
            dplyr::filter( list_name ==   list_namei) |>
            dplyr::select( name, label)  |>
            dplyr::distinct() 
    labelrecode <- stats::setNames(as.character(nlevel_likert$label), nlevel_likert$name)
          
    ##  Subsetting data - checking levels - and applying label
    var <- as.data.frame(dico[["variables"]]) |>
                 dplyr::filter( list_name ==  list_namei &
                                scope == scopei  &
                                repeatvar == repeatvari  &
                                appearance != "label" )
    ## Just in case with have the first one being appearance label
    data <-kobo_frame(datalist = datalist, dico = dico, var = var[2, c("name")])
      
    likertframe <- data |>
            ## select only likert variable
            dplyr::select ( tidyselect::any_of( c(var$name)) ) |>
            ## Ensure they all have the same levels as factor
            dplyr::mutate_all(dplyr::funs(factor(., levels =c(nlevel_likert$name ))))  |>
            ## Recode variable with the label
            dplyr::mutate_all(dplyr::funs(dplyr::recode(., !!!labelrecode)))  |>
            #mutate_all(dplyr::recode( !!!labelrecode)) |>
            ## convert to dataframe to ensure likert() works
            as.data.frame() |> 
            ## remove potential var used for appearance 'label'
            dplyr::select_if(~!all(is.na(.))) |>
            ## Remove records where all na
            dplyr::filter(dplyr::if_any(dplyr::everything(), ~ !is.na(.)))
    
    
     
    if( nrow(likertframe) == 0 ) {
      cat("Chart could not be generated")
    } else {
      
     ## Replace with label for the variable 
     for ( j in 1:ncol(likertframe)){
       # j <- 1
       newname <- as.character(var[ var$name == names(likertframe)[j] , c("label")  ])
       names(likertframe)[j] <- newname
     }  
                                        
          # Build likert object
          likertframe.obj <- likert::likert(likertframe)
      
          ## get response rate
          rr <- nrow(likertframe)/ nrow(data)
          
          ## Now generate the plot
        a <- plot(likertframe.obj,
                  #center = 2,
                  wrap= 70) +
          ggplot2::labs(title = labelgroup, 
               caption = glue::glue("Response rate = {scales::label_percent(accuracy = .01)(rr)}, {nrow(likertframe)} on a total of {nrow(data)} records. \n Source: {datasource}"))+
          # guides(fill=guide_legend(title=NULL),    color=guide_legend(nrow=2, byrow=TRUE))  +
          #unhcrthemes::theme_unhcr(grid="X") +
          ggplot2::theme_minimal( base_size = 22) +
          ggplot2::theme( #plot.title=element_text(size=32, face="bold", color="black"), 
                 #plot.subtitle=element_text(size=19, face="italic", color="black"), 
                #text = element_text(size=22, color = "#333333"), 
                #legend.position="right",legend.direction="vertical"), legend.margin=margin()
                legend.position="bottom",
                legend.box="vertical")
        
        ## Extract the legend to put it fully belwo the main chart
        p1_legend <- cowplot::get_legend(a + 
                                  ggplot2::theme(legend.position="bottom", legend.box="vertical", legend.margin=ggplot2::margin(t = 0, unit='cm')) )
        
        #cowplot::ggdraw(p1_legend)
        p <-  cowplot::plot_grid(a +  ggplot2::theme(legend.position = 'none'), 
                                  p1_legend ,
                                  nrow = 2, 
                                  rel_heights = c(1, 0.1))
          
    return(p)      
        
    } 
        
    
}

