# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' @title Plotting numeric variable
#' @param datapath path to the file with the data format as extracted from kobo with dot as group separator and xml header
#' @param xlsformpath path to the xlsform file used to cole
#' @param var name of the variable to display
#' @param by_var variable to use for cross tabulation
#' @param showcode display the code
#' @export

#' @examples
#' plot_integer_cross(datapath = system.file("data.xlsx", package = "kobocruncher"),
#'               xlsformpath =  system.file("sample_xlsform.xlsx", package = "kobocruncher"), 
#'               var = "members.age",
#'               by_var = "members.sex")
plot_integer_cross <- function(datapath = datapath, 
                         xlsformpath = xlsformpath,
                         var, 
                         by_var ,
                         showcode = FALSE) {
  
  require("ggplot2")
  dico <-  kobo_dico(xlsformpath = xlsformpath)
  datasource <- as.character(  dico[3][[1]]$form_title ) 
  data <- kobo_frame(datapath = datapath,
                   xlsformpath = xlsformpath,
                   var = var  )
  ## Cast just in case...
  data[[var]] <- as.integer(data[[var]])
  ## get response rate: rr
  rr <- mean(!is.na(data[[var]]))
  # cat("---\n")
  # cat("\n\n")
 if ( is.nan(rr)) {
    cat("<strong style=\"color:#0072BC;\">This variable could not be identified in the dataset</strong>\n\n")
  } else {
  
  ## Writing report
  if (rr != 0 & ! (is.nan(rr)) ) { 
      ## Writing code instruction in report
      if( showcode == TRUE) {
        cat(paste0(fontawesome::fa_png("far fa-copy", fill ="grey"),"  `plot_integer(datapath = datapath, xlsformpath = xlsformpath, \"", var, "\")` \n\n "))}    else {}
    
    p <- ggplot(data) + 
      geom_boxplot(aes(x = .data[[var]], y =  .data[[by_var]]), 
                     fill = "#0072BC", 
                     color = "white" 
      ) +
      # scale_y_continuous(labels = scales::label_percent()) +
      labs(x = NULL, y = NULL,
             title = stringr::str_wrap(label_varname(xlsformpath = xlsformpath, 
                                                         x = var), 80),
             subtitle = stringr::str_wrap( paste0("Crossed by ", label_varname(xlsformpath = xlsformpath,
                                                         x = by_var)), 80),
           caption = glue::glue("Numeric response, Response rate = {scales::label_percent(accuracy = .01)(rr)} on a total of {nrow(data)} records \n Source: {datasource}")) +
      
      scale_size_area(max_size = 10) +        
      scale_y_discrete(labels = function(x) {label_choiceset(xlsformpath = xlsformpath,
                                                          x = var)(x) |>
            stringr::str_wrap(40)}) +
      theme_minimal( base_size = 13) +
      geom_hline(yintercept = 0, size = 1.1, colour = "#333333") +
      theme( panel.grid.major.y  = element_line(color = "#cbcbcb"), 
           panel.grid.major.x  = element_blank(), 
           panel.grid.minor = element_blank()    ) +
           theme(plot.title.position = "plot")
    
    print(p)
    
    } else { cat("<strong style=\"color:#0072BC;\">No recorded answers for this specific question!</strong>\n\n")}
  # cat("\n\n")
  }
}

