# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' @title Plotting Likert
#' 
#' @description Detect if we have more than 3 questions with the same response options within the same questions group
#' and represent the result using a standard likert plot - build from  https://github.com/jbryer/likert
#' 
#' @param datalist An object of the "datalist" class as defined in kobocruncher 
#' @param dico An object of the "kobodico" class format as defined in kobocruncher
#' @export

plot_likert <- function(datalist = datalist,
                        dico = dico) {

  require(dplyr)
    require(ggplot2)
  require(likert) 
  ## Check the frequency of list_name within each group,
  ## Filter the combination of list and group where we have more than 3 occurrences
  # not taking in account when the appearance is not "label"
  grouplikert <- as.data.frame(dico[1]) |>
    dplyr::filter( type ==  "select_one") |>
    dplyr::filter( appearance !=  "label") |>
    dplyr::group_by( scope, list_name) |>
    dplyr::summarise( cnt= dplyr::n() )|>
    dplyr::filter( cnt >= 3)

  for (i in 1:nrow(grouplikert)  ) {
    ## getting the group and corresponding label
    scopei <-   as.character(grouplikert[i, c("scope")])
    labelgroup <- as.data.frame(dico[1]) |>
      dplyr::filter( name  %in%  c(scopei)) |>
      dplyr::select( label) |>
      dplyr::pull()
    
    ## geting the list_name and corresponding label
    list_namei <- as.character( grouplikert[i, c("list_name")])
    nlevel_likert <- as.data.frame(dico[2]) |>
      dplyr::filter( list_name ==   list_namei) |>
      dplyr::select( name, label)  |>
      dplyr::distinct() 
    labelrecode <- stats::setNames(as.character(nlevel_likert$label), nlevel_likert$name)
    
    ##  Subsetting data - checking levels - and applying label
    var <- as.data.frame(dico[1]) |>
           dplyr::filter( list_name ==  list_namei &
                          scope == scopei  &
                          appearance !="label" )
    data <-kobo_frame(datalist = datalist, dico = dico, var = var[1, c("name")])

    likertframe <- data |>
      ## select only likert variable
      dplyr::select ( tidyselect::any_of( c(var$name)) ) |>
      ## Ensure they all have the same levels as factor
      mutate_all(funs(factor(., levels =c(nlevel_likert$name ))))  |>
      ## Recode variable with the label
      mutate_all(funs(dplyr::recode(., !!!labelrecode)))  |>
      #mutate_all(dplyr::recode( !!!labelrecode)) |>
      ## convert to dataframe to ensure likert() works
      as.data.frame()
    ## Replace with label for the variable 
    names(likertframe) <- var$label
                                  
    # Build likert object
    likertframe.obj <- likert::likert(likertframe)

    ## Now generate the plot
    print(plot(likertframe.obj,
               #center = 2,
               wrap= 90) +
            labs(title = labelgroup) 
    )
  }
}

