# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' @title Plotting Select one variable
#' @param datapath path to the file with the data format as extracted from kobo with dot as group separator and xml header
#' @param xlsformpath path to the xlsform file used to cole
#' @param var name of the variable to display
#' @param crosstab variable to use for cross tabulation
#' @param showcode display the code
#' @export

#' @examples
#' plot_select_one_cross(datapath = system.file("data.xlsx", package = "koboloadeR"),
#'               xlsformpath =  system.file("sample_xlsform.xlsx", package = "koboloadeR"), 
#'               var = "profile.country",
#'               crosstab = "profile.occupation"
#'               )
plot_select_one_cross <- function(datapath = datapath,
                            xlsformpath = xlsformpath,
                            var, 
                            crosstab , 
                            showcode = FALSE) {
  
  require("ggplot2")
  
  dico <-  kobo_dico(xlsformpath = xlsformpath)
  datasource <- as.character(  dico[3][[1]]$form_title ) 
  data <- kobo_frame(datapath = datapath,
                   xlsformpath = xlsformpath,
                   var = var  )
  ## get response rate: rr
  rr <- mean(!is.na(data[[var]]))
  ## Writing report
  # cat("\n")
 # cat(paste("####", label_varname(var)))
  #cat(paste("#### Variable: ", var))
  ## Put a condition in case there's no record
  if (rr != 0 ) { 
    if(crosstab != "") {
      if( crosstab != var ) {
        
          ## Writing code instruction in report
          if( showcode == TRUE) {
            
            cat(paste0("  `plot_select_one_cross(\"", var, "\",\"", crosstab, "\")` \n\n "))} 
            # #cat("---\n")
            #  cat(paste0("##### ",fontawesome::fa_png("far fa-copy", fill ="grey"), " `plot_select_one_cross(\"", var, "\",\"", crosstab, "\")`  " ))
            # cat("\n\n") } 
          else {}

      cnts <- data |>
        ## keep only the variable we need
        tidyr::drop_na(tidyselect::all_of(c(var,crosstab))) |>
        # Lump together factor levels into "other"
        dplyr::count(x := forcats::fct_lump_n(factor(.data[[var]]), n = 5),
                     y := forcats::fct_lump_n(factor(.data[[crosstab]]), n = 5) ) |>
        dplyr::mutate(p = n/sum(n)) |>
        dplyr::group_by(y) |>
        dplyr::mutate(cumsum = max(cumsum(as.numeric(n))),
                      pcum = n / cumsum)  
       
       ## plot
       p <- ggplot(cnts, 
                  aes(x= pcum, 
                      y = x)) +
        geom_col(fill = "#0072BC") +
        #geom_label(aes(label = scales::label_percent(accuracy = .01)(pcum)), size = 2) +
        ## Position label differently in the bar in white - outside bar in black
        geom_label( data =   function(x) subset(x, pcum < max(pcum) / 1.5),
                    aes(label = scales::label_percent(accuracy = .01)(pcum)),
                    hjust = -0.1 ,
                    vjust = 0.5, 
                    colour = "black", 
                    fill = NA, 
                    label.size = NA, 
                     
                    size = 3   ) +  
        geom_label( data =   function(x) subset(x, pcum >= max(pcum) / 1.5),
                    aes(label = scales::label_percent(accuracy = .01)(pcum)),
                    hjust = 1.1 ,
                    vjust = 0.5, 
                    colour = "white", 
                    fill = NA, 
                    label.size = NA, 
                     
                    size = 3   ) +   
        scale_x_continuous(labels = scales::label_percent()) +
         
        facet_wrap( ~ y ,  nrow = 3 # ,
          #             labeller = as_labeller(function(x) label_choice(xlsformpath = xlsformpath, 
          #                                                             choices = choices,
          #                                                             var = crosstab)(x))
          ) +
          # scale_y_discrete(labels = function(x) {label_choice(xlsformpath = xlsformpath, 
          #                                                   choices = choices,
          #                                                   var = var)(x) |>
          #     stringr::str_wrap(40)}) +
        coord_cartesian(clip = "off") +
        labs(x = NULL, y = NULL,
               title = stringr::str_wrap(label_varname(xlsformpath = xlsformpath,
                                                       x = var), 80),
               subtitle = stringr::str_wrap( paste0("Crossed by ", label_varname(xlsformpath = xlsformpath,
                                                                                 x = crosstab)), 80),
               caption = glue::glue("Single choice question, Response rate = {scales::label_percent(accuracy = .01)(rr)} on a total of {nrow(data)} records \n Source: {datasource}")) +
        theme_minimal( base_size = 13) +  
        geom_vline(xintercept = 0, size = 1.1, colour = "#333333") +
        theme( panel.grid.major.x  = element_line(color = "#cbcbcb"), 
                 panel.grid.major.y  = element_blank(), 
                 panel.grid.minor = element_blank()    ) +
        theme(plot.title.position = "plot")

        print(p)
    
      }
    } else { }
  } else { cat("<strong style=\"color:#0072BC;\">No recorded answers for this specific question!</strong> \n\n")}
  # cat("\n\n")
}


