# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' @title Plotting Correlation
#' 
#' @description blbla
#' 
#' @param datalist An object of the "datalist" class as defined in kobocruncher 
#' @param dico An object of the "kobodico" class format as defined in kobocruncher
#' @param var name of the variable to display
#' @param by_var variable to use for cross tabulation
#' @param showcode display the code
#' @export

#' @examples
#' dico <- kobo_dico( xlsformpath = system.file("sample_xlsform.xlsx", package = "kobocruncher") )
#' datalist <- kobo_data(datapath = system.file("data.xlsx", package = "kobocruncher") )
#' 
#' plot_correlation(datalist = datalist,
#'               dico = dico, 
#'               var = "profile.occupation",
#'               by_var = "profile.country")
plot_correlation <- function(datalist = datalist, 
                             dico = dico,
                             var, 
                             by_var, 
                             showcode = FALSE) {
  
       ## verify they are in the same frame
       frame1 <- kobo_frame(datalist = datalist,
                            dico = dico,
                            var = var) 
       frame2 <- kobo_frame(datalist = datalist,
                            dico = dico,
                            var = by_var ) 
       
     if(by_var != var & !( identical(frame1, frame2)) )
      { cat("the two variables are identical or not in the same data framee")
      } else {
       formula <- frame1 |>
       dplyr::select(var, by_var) 
       names(formula)[1] <- "target"
       names(formula)[2] <- "tested"
       
       ## Check that each class is represented
       check.class <- as.data.frame(table(formula$target,formula$tested))
       n.class <- nrow(check.class)
       n.class.notnull <- nrow(check.class[check.class$Freq > 0, ])
      
       ### Testing number of levels for the 2 variables as 'x' and 'y' must have at least 2 levels
       if ( ## We need at least 2 levels
        ( nlevels(as.factor(as.character(formula$target))) > 1 ) &
        ( nlevels(as.factor(as.character(formula$tested))) > 1 ) &
           ## If too many levels - more than 8, the corrogram is not legible...
        ( nlevels(as.factor(as.character(formula$target))) < 8 ) &
        ( nlevels(as.factor(as.character(formula$tested))) < 8 ) #&
          ## May have class with zero value...
         # n.class == n.class.notnull
        ) { 
       
        p.value  <- round(stats::chisq.test(formula$target,formula$tested)$p.value,4)   ### Case there not any positive test
        if (p.value <= 0.05 ) {
                 cat("No significant association found for this question...\n")
          } else {
          ## now generating correlation plot 
          corrplot::corrplot(stats::chisq.test(formula$target,formula$tested)$residuals,
                 is.cor = FALSE, # use for general matrix to convert to Sq form
                 cl.pos = "n", ## Do not display the color legend
                 cl.cex = 0.7, # Size of all label
                 tl.cex = 0.7, # Size of axis label
                 tl.srt = 45, # string rotation in degrees
                 tl.col = "black", # color of text label.
                 addCoef.col = "grey", # add coeff in the chart
                 number.cex = 3/ncol(stats::chisq.test(formula$target,formula$tested)), # size of coeff
                 mar = c(0.5,0.5,4, 0.5), ## margin of plots
                 title = paste0("Statistical Association between: \n ", 
                                label_varname(dico = dico,  x = var),
                                "[row] & ",
                                label_varname(dico = dico, x = by_var), "[col]" ))

           
          } }  
       else { cat("there are either too many or not enough level to perform this analysis.. Clean your data.\n") } 
     }
    
}

