# WARNING - Generated by {fusen} from dev/flat_dev.Rmd: do not edit by hand

#' @title Plotting numeric variable
#' @param datalist An object of the "datalist" class as defined in kobocruncher 
#' @param dico An object of the "kobodico" class format as defined in kobocruncher
#' @param var name of the variable to display
#' @param datasource name of the data source to display, if set to NULL - then pulls the form_title within the settings of the xlsform 
#' @param showcode display the code
#' 
#' @import ggplot2 
#' @import dplyr
#' @importFrom datawizard skewness kurtosis
#' @importFrom stats IQR   
# prefixer::import_from(fun = kobo_dico)          
#' 
#' @export
#' @examples
#' dico <- kobo_dico( xlsformpath = system.file("sample_xlsform.xlsx", package = "kobocruncher") )
#' datalist <- kobo_data(datapath = system.file("data.xlsx", package = "kobocruncher") )
#'
#' plot_integer(datalist = datalist,
#'               dico = dico, 
#'               var = "members.age",
#'               showcode = TRUE)

plot_integer <- function(datalist = datalist, 
                         dico = dico,
                         var, 
                         datasource = NULL,
                         showcode = FALSE) {
  
  #requireNamespace("ggplot2") 
  #requireNamespace("dplyr")
  ## Get default data source name 
  if( is.null(datasource)) {datasource <- as.character(  dico[[3]]$form_title ) }
   
  data <- kobo_frame(datalist = datalist,
                   dico = dico,
                   var = var  )
  ## Cast just in case...
  data[[var]] <- as.numeric(data[[var]])
  ## get response rate: rr
  rr <- mean(!is.na(data[[var]]))
  # cat("---\n")
  # cat("\n\n")
 if ( is.nan(rr)) {
    cat(paste0("<strong style=\"color:#0072BC;\">The variable from the form called: ",var," could not be identified in the dataset</strong>\n\n"))
      return(invisible())
     #return(invisible(NULL))
  } else {
  
  ## Writing report
  if (rr != 0 & ! (is.nan(rr))  ) { 
      ## Writing code instruction in report
      if( showcode == TRUE) {
        cat(paste0(label_varname(dico = dico,
                                                   x = var), "\n",
    "`plot_integer(datalist, dico, \"", var, "\", datasource=params$datasource)` \n\n "))  }   else {}  
    
    
     info <- paste0("Mean: ", round(mean(data[[var]], na.rm = TRUE),2) ,
                    ", Standard Deviation: ",round(stats::sd(data[[var]], na.rm = TRUE),2) ,
                    ", Coefficient of Variation: ",round( stats::sd(data[[var]], na.rm = TRUE) / mean(data[[var]], na.rm = TRUE) * 100 ,2) ,
                    ", Skewness: ",round(datawizard::skewness(data[[var]], remove_na = TRUE),2) ,
                    " and Kurtosis: ",round(datawizard::kurtosis(data[[var]], remove_na = TRUE),2), ".")
     ## Detect potential outliers based on Interquartile Range
     iqr <- stats::IQR(data[[var]], na.rm = T)
     infoIQR <- dplyr::if_else ( iqr >= 1.349,
        paste0("Interquartile Range is ", round(iqr,2), " which suggests that there is no outlier"),
        paste0("Interquartile Range is ", round(iqr,2), " which suggests that there are outliers"))
                 
    
    #require(ggplot2)
    p <- ggplot2::ggplot(data) + 
      ggplot2::geom_histogram(ggplot2::aes( x= .data[[var]]), 
                    # bins = nclass.FD(na.omit(data[[var]])),
                     fill = "#0072BC", 
                     color = "white" 
      ) +
      # scale_y_continuous(labels = scales::label_percent()) +
      ggplot2::labs(x = NULL, y = NULL,
           title = stringr::str_wrap(label_varname(dico = dico, x = var), 90), 
           subtitle = if (!is.na(label_varhint(dico = dico, x = var))){ 
                     stringr::str_wrap(label_varhint(dico = dico, x = var), 90)} else { ""},
           caption = stringr::str_wrap(glue::glue("Numeric, Response rate = {scales::label_percent(accuracy = .01)(rr)} on a total of {nrow(data)} records \n Source: {datasource} - {info} - {infoIQR}")), 100) +
  
      ggplot2::theme_minimal( base_size = 24) +
     # geom_hline(yintercept = 0, size = 1.1, colour = "#333333") +
      ggplot2::theme( panel.grid.major.y  = ggplot2::element_line(color = "#cbcbcb"), 
           panel.grid.major.x  = ggplot2::element_blank(), 
           panel.grid.minor = ggplot2::element_blank()    ) +
           ggplot2::theme(plot.title.position = "plot")
    
   return(p) #  print(p)
    
  } else { 
    cat(paste0("<strong style=\"color:#0072BC;\"> No recorded answers for the question: </strong>",var,"\n\n"))
      return(invisible())
    #return(invisible(NULL))  
    }
  # cat("\n\n")
  }
}



