# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' @title Plotting Select one variable
#' @description Note that if the column order is set in the xlsform choice part, the variable will be de factor considered as ordinal and the default ordering will not be done based on frequency
#' @param datalist An object of the "datalist" class as defined in kobocruncher 
#' @param dico An object of the "kobodico" class format as defined in kobocruncher
#' @param var name of the variable to display
#' @param datasource name of the data source to display, if set to NULL - then pulls the form_title within the settings of the xlsform 
#' @param n if not NULL, lumps all levels except for the n most frequent (or least frequent if n < 0) - cf
#'            forcats::fct_lump_n()
#' @param showcode display the code
#' 
#' @importFrom ggplot2 aes  geom_col geom_label scale_x_continuous scale_y_discrete coord_cartesian labs theme_minimal geom_vline theme element_line element_blank
#' @importFrom data.table := 
#' 
#' @export
# prefixer::import_from(fun = kobo_dico)

#' @examples
#' dico <- kobo_dico( xlsformpath = system.file("sample_xlsform.xlsx", package = "kobocruncher") )
#' datalist <- kobo_data(datapath = system.file("data.xlsx", package = "kobocruncher") )
#' 
#' plot_select_one(datalist = datalist,
#'               dico = dico, 
#'               var = "profile.country",
#'               showcode = TRUE)
#' ## Exmaple with lumping
#' plot_select_one(datalist = datalist,
#'               dico = dico, 
#'               var = "profile.country",
#'               n = 1,
#'               showcode = TRUE)
#' 
#' # plot_select_one(datalist = datalist,
#' #               dico = dico, 
#' #               var = "profile.countryerror",
#' #               showcode = TRUE)
plot_select_one <- function(datalist  ,
                            dico  ,
                            var,
                            datasource = NULL,
                            n = NULL, 
                            showcode = FALSE) {

  requireNamespace("ggplot2")
  requireNamespace("dplyr")
  ## Get default data source name 
  if( is.null(datasource)) {datasource <- as.character(  dico[[3]]$form_title ) }
  
 
  data <- kobo_frame(datalist = datalist,
                   dico = dico,
                   var = var  )
  
  ## get response rate: rr
  rr <- mean(!is.na(data[[var]]))
  ## get number of non NA response
  nr <- sum(!is.na(data[[var]]))
  
  if ( is.nan(rr)) {
    cat(paste0("\n <strong style=\"color:#0072BC;\">The variable from the form called: ",var," could not be identified in the dataset</strong>\n\n"))
   # return(invisible(NULL))
     return(invisible())
    
  } else {
  
  ## Put a condition in case there's no record
  if (rr != 0  & ! (is.nan(rr)) ) {
    
  
  ## Count number of levels   
  nlev <-  nlevels( as.factor(data[[var]]) )  
  ## Set the value for n if not set up -
  if( is.null(n)) { n1 = nlev } else { n1 = n}
  
  cnts <- data |>
    tidyr::drop_na(tidyselect::all_of(var)) |>
    dplyr::group_by(.data[[var]]) |>
    #dplyr::summarise(n = dplyr::n()) |>
    dplyr::count(x := .data[[var]]) |>
    dplyr::mutate(p = n/nr) |>
    # Lump together factor levels into "other"
    dplyr::mutate(x = forcats::fct_lump_n( as.factor(x),    
                                         n = as.integer(n1),
                                         w = p,
                     other_level = paste0("Other ",
                              nlev  - n1,
                              " response options automatically lumped") )) |>
    dplyr::group_by(x) |>
    dplyr::summarise( n = sum(n, na.rm = TRUE),
                      p = n/nr)
  
  
  
  listvar <- as.data.frame(dico[["variables"]]) |>
             dplyr::filter( name ==var ) |>
             dplyr::pull(list_name)
  
  ## Manage situation if ordinal variable (i.e. order is set in choices)
  if (any(!is.na(dplyr::filter(dico[[2]], list_name == listvar)$order))) {
    
    
    ## case there are duplicated answers options - for instance if allow_choice_duplicates = yes
    ll <- dplyr::filter(dico[[2]], list_name == listvar) |>
          dplyr::group_by(name) |> 
          dplyr::slice_head(n = 1)
    
    cnts <- cnts |>
          dplyr::left_join( ll, by = c("x"="name"))|>
          dplyr::mutate(x = forcats::fct_reorder(x, order, as.numeric))
  } else {
    cnts <- cnts |>
      dplyr::mutate(x = forcats::fct_reorder(x, n))
  }
  
  ## Writing code instruction in report
  if( showcode == TRUE) { cat(paste0("\n", label_varname(dico = dico,
                                                   x = var), "\n",
                                      
     "`plot_select_one(datalist, dico, \"", var, "\", datasource = params$datasource, n = ",n1, ")` \n\n ")) }  else {}
  
    
    ## plot
    require(ggplot2)
    p <- ggplot2::ggplot(cnts, ggplot2::aes(p, x)) +
      ggplot2::geom_col(fill = "#0072BC") +
      
      #geom_label(aes(label = scales::label_percent(accuracy = .01)(p))) +
      ## Position label differently in the bar in white - outside bar in black
      ggplot2::geom_label( data =   function(x) subset(x, p < max(p) / 1.5),
                  ggplot2::aes(label = scales::label_percent(accuracy = .01)(p)),
                  hjust = -0.1 ,
                  vjust = 0.5,
                  colour = "black",
                  fill = NA,
                  label.size = NA,
                  size = 6   ) +
      ggplot2::geom_label( data =   function(x) subset(x, p >= max(p) / 1.5),
                  ggplot2::aes(label = scales::label_percent(accuracy = .01)(p)),
                  hjust = 1.1 ,
                  vjust = 0.5,
                  colour = "white",
                  fill = NA,
                  label.size = NA,
                  size = 6   ) +
      ggplot2::scale_x_continuous(labels = scales::label_percent()) +
      ggplot2::scale_y_discrete(labels = function(x) {label_choiceset(dico = dico, x = var)(x) |>
                      stringr::str_wrap(40)}) +
      ggplot2::coord_cartesian(clip = "off") +
      ggplot2::labs(x = NULL, y = NULL,
           title = stringr::str_wrap(label_varname(dico = dico, x = var), 90),
           subtitle = if (!is.na(label_varhint(dico = dico, x= var))){
                      stringr::str_wrap(label_varhint(dico = dico, x= var), 90)} else { ""},
           caption = glue::glue("Single choice, Response rate = {scales::label_percent(accuracy = .01)(rr)}  on a total of {nrow(data)} records. \n Source: {datasource}")) +
      ggplot2::theme_minimal( base_size = 24) +
      ggplot2::geom_vline(xintercept = 0, size = 1.1, colour = "#333333") +
      ggplot2::theme( panel.grid.major.x  = ggplot2::element_line(color = "#cbcbcb"),
             panel.grid.major.y  = ggplot2::element_blank(),
             panel.grid.minor = ggplot2::element_blank()    ) +
      ggplot2::theme(plot.title.position = "plot")
    
   return(p) #  print(p)
    
  } else { 
    cat(paste0("<strong style=\"color:#0072BC;\"> No recorded answers for the question: </strong>",var,"\n\n")) 
      #return(invisible(NULL))
      return(invisible())
    }
  # cat("\n\n")
  }
}  



