# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' @title Plotting numeric variable
#' @param datalist An object of the "datalist" class as defined in kobocruncher 
#' @param dico An object of the "kobodico" class format as defined in kobocruncher
#' @param var name of the variable to display
#' @param by_var variable to use for cross tabulation
#' @param datasource name of the data source to display, if set to NULL - then pulls the form_title within the settings of the xlsform 
#' @param showcode display the code
#' 
#' @importFrom   ggplot2 theme element_line element_blank element_text aes labs
#'             theme_minimal geom_hline geom_boxplot scale_size_area 
#'              scale_y_discrete theme_minimal
#' @export

#' @examples
#' dico <- kobo_dico( xlsformpath = system.file("sample_xlsform.xlsx", package = "kobocruncher") )
#' datalist <- kobo_data(datapath = system.file("data.xlsx", package = "kobocruncher") )
#' 
#' plot_integer_cross(datalist = datalist,
#'               dico = dico, 
#'               var = "members.age",
#'               by_var = "members.sex",
#'               showcode = TRUE)
plot_integer_cross <- function(datalist = datalist, 
                         dico = dico,
                         var, 
                         by_var ,
                         datasource = NULL,
                         showcode = FALSE) {
  
  requireNamespace("ggplot2")
  requireNamespace("dplyr")
  ## Get default data source name 
  if( is.null(datasource)) {datasource <- as.character(  dico[3][[1]]$form_title ) }
  
  data <- kobo_frame(datalist = datalist,
                   dico = dico,
                   var = var  )
  ## Cast just in case...
  data[[var]] <- as.integer(data[[var]])
  ## get response rate: rr
  rr <- mean(!is.na(data[[var]]))
  
   data2 <- kobo_frame(datalist = datalist,
                   dico = dico,
                   var = by_var   )
  
  ## get response rate: rr
  rr <- mean(!is.na(data[[var]]))
  rr2 <- mean(!is.na(data2[[by_var]]))
  ## Writing report
  # cat("\n")
 # cat(paste("####", label_varname(var)))
  #cat(paste("#### Variable: ", var))
  
  if ( is.nan(rr) | is.nan(rr2) ) {
    cat(paste0("<strong style=\"color:#0072BC;\">The variable from the form called: ",var," or ", by_var, " could not be identified in the dataset</strong>\n\n"))
  } else if (  ! (identical(data,data2))  ) {
    # nothing to do - the variable are not in the same frame
    } else {
  
  ## Writing report
  if (rr != 0 & ! (is.nan(rr)) ) { 
      ## Writing code instruction in report
      if( showcode == TRUE) {
        cat(paste0(label_varname(dico = dico,
                                                   x = var), "\n",
                                      fontawesome::fa("far fa-copy", fill ="grey"),"  `plot_integer(datalist = datalist, dico = dico, \"", var, "\")` \n\n "))}    else {}
    
    require(ggplot2)
    p <- ggplot2::ggplot(data) + 
      geom_boxplot(aes(x = .data[[var]], y =  .data[[by_var]]), 
                     fill = "#0072BC", 
                     color = "white" 
      ) +
      # scale_y_continuous(labels = scales::label_percent()) +
      labs(x = NULL, y = NULL,
          title = stringr::str_wrap(label_varname(dico = dico, x = var), 90),
          subtitle = stringr::str_wrap( paste0("Crossed by ", label_varname(dico = dico, x = by_var)), 90),
          caption = glue::glue("Numeric response, Response rate = {scales::label_percent(accuracy = .01)(rr)} on a total of {nrow(data)} records \n Source: {datasource}")) +
      
      scale_size_area(max_size = 10) +        
      scale_y_discrete(labels = function(x) {label_choiceset(dico = dico,
                                                          x = var)(x) |>
            stringr::str_wrap(40)}) +
      theme_minimal( base_size = 24) +
      geom_hline(yintercept = 0, size = 1.1, colour = "#333333") +
      theme( panel.grid.major.y  = element_line(color = "#cbcbcb"), 
           panel.grid.major.x  = element_blank(), 
           panel.grid.minor = element_blank()    ) +
           theme(plot.title.position = "plot")
    
   return(p) #  print(p)
    
    } else { cat(paste0("<strong style=\"color:#0072BC;\"> No recorded answers for the question: </strong>",var,"\n\n")) }
  # cat("\n\n")
  }
}

