# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' @title Plotting Select multiple variable
#' @param datapath path to the file with the data format as extracted from kobo with dot as group separator and xml header
#' @param xlsformpath path to the xlsform file used to cole
#' @param var name of the variable to display
#' @param showcode display the code
#' @export

#' @examples
#' plot_select_multiple(datapath = system.file("data.xlsx", package = "koboloadeR"),
#'               xlsformpath =  system.file("sample_xlsform.xlsx", package = "koboloadeR"), 
#'               var = "profile.reason"
#'             )
plot_select_multiple <- function(datapath = datapath, 
                                 xlsformpath = xlsformpath,
                                 var, 
                                 showcode = FALSE) {
  
  require("ggplot2")
  
  dico <-  kobo_dico(xlsformpath = xlsformpath)
  datasource <- as.character(  dico[3][[1]]$form_title ) 
  data <- kobo_frame(datapath = datapath,
                   xlsformpath = xlsformpath,
                   var = var  )
  
  ## get response rate: rr
  rr <- mean(!is.na(data[[var]]))
  nr <- sum(!is.na(data[[var]]))
  cnts <- data |>
    tidyr::drop_na(tidyselect::all_of(var)) |>
    tidyr::separate_rows(.data[[var]], sep = " ") |>
    # Lump together factor levels into "other"
    dplyr::distinct(`X_id`, !!var := forcats::fct_lump_n(factor(.data[[var]]), n = 5)) |>
    dplyr::count(x := .data[[var]]) |>
    dplyr::mutate(p = n/nr)
  
  ## Manage situation if ordinal variable (i.e. order is set in choices)
  if (any(!is.na(label_choiceset(xlsformpath = xlsformpath,
                           x = var)$order))) {
    cnts <- cnts |>
    dplyr::mutate(x = factor(x, 
                             levels = c(label_choiceset(xlsformpath = xlsformpath,
                                                          x = var)$name, "Other")))
   } else {
    cnts <- cnts |>
             dplyr::mutate(x = factor(x,  
                             levels = x[order(n, decreasing=FALSE)]))
  }

  ## If not empty
  if (rr != 0 ) {  
    
    ## Writing code instruction in report
    if( showcode == TRUE) {
      cat(paste0("  `plot_select_multiple(\"", var, "\")` \n\n "))} 
      #cat("---\n")
      #  cat(paste0("##### ",fontawesome::fa_png("far fa-copy", fill ="grey"), "  `plot_select_multiple(\"", var, "\")`  "))
      # cat("\n\n") } 
    else {} 
    
    ## Plot
     p <- ggplot(cnts, aes(p, x)) +
      geom_col(fill = "#0072BC") +
      #geom_label(aes(label = scales::label_percent(accuracy = .01)(p))) + 
      ## Position label differently in the bar in white - outside bar in black
      geom_label( data =   function(x) subset(x, p < max(p) / 1.5),
                    aes(label = scales::label_percent(accuracy = .01)(p)),
                    hjust = -0.1 ,
                    vjust = 0.5, 
                    colour = "black", 
                    fill = NA, 
                    label.size = NA, 
                     
                    size = 4   ) +  
      geom_label( data =   function(x) subset(x, p >= max(p) / 1.5),
                    aes(label = scales::label_percent(accuracy = .01)(p)),
                    hjust = 1.1 ,
                    vjust = 0.5, 
                    colour = "white", 
                    fill = NA, 
                    label.size = NA, 
                     
                    size = 4   ) +   
      
      scale_x_continuous(labels = scales::label_percent()) +
      # scale_y_discrete(labels = function(x) {label_choice(xlsformpath = xlsformpath,
      #                                                   x = var)(x) |>
      #     stringr::str_wrap(40)}) +
      coord_cartesian(clip = "off") +
      labs(x = NULL, y = NULL,
           title = stringr::str_wrap(label_varname(xlsformpath = xlsformpath,
                                                         x= var), 60),
           subtitle = if (!is.na(label_varhint(xlsformpath = xlsformpath,
                                                        x = var))){ 
                     stringr::str_wrap(label_varhint(xlsformpath = xlsformpath,
                                                          x = var), 70)} else { ""},
           caption = glue::glue("Multiple choice question, Response rate = {scales::label_percent(accuracy = .01)(rr)} on a total of {nrow(data)} records \n Source: {datasource}")) +
      theme_minimal( base_size = 15) + 
      geom_vline(xintercept = 0, size = 1.1, colour = "#333333") +
      theme( panel.grid.major.x  = element_line(color = "#cbcbcb"), 
             panel.grid.major.y  = element_blank(), 
             panel.grid.minor = element_blank()    ) +
      theme(plot.title.position = "plot")
     
     
    print(p)
    
    #plot_select_multiple_cross(var,   crosstab)
    
  } else { cat("<strong style=\"color:#0072BC;\">No recorded answers for this specific question!</strong> \n\n")}
  # cat("\n\n")
}

