# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' @title Plotting Select one variable with cross tabulation on a second categorical variable
#' @description
#' Note that if the column order is set in the xlsform choice part, the variable will be de factor considered as ordinal and the default ordering will not be done based on frequency
#' @param datalist An object of the "datalist" class as defined in kobocruncher 
#' @param dico An object of the "kobodico" class format as defined in kobocruncher
#' @param var name of the variable to display
#' @param by_var variable to use for cross tabulation
#' @param datasource name of the data source to display, if set to NULL - then pulls the form_title within the settings of the xlsform 
#' @param n if not NULL, lumps all levels except for the n most frequent (or least frequent if n < 0) - cf
#'            forcats::fct_lump_n()
#' @param n_by if not NULL, lumps all levels for the cross tabulation variable except for the n_by most frequent (or least frequent if n < 0) - cf
#'            forcats::fct_lump_n()
#' @param showcode display the code
#' 
#' @importFrom ggplot2 aes  geom_col geom_label 
#'             scale_x_continuous scale_y_discrete 
#'             coord_cartesian labs theme_minimal 
#'             geom_vline theme element_line element_blank
#'             as_labeller facet_wrap
#' @importFrom data.table :=  
#' @export

# prefixer::import_from(fun = plot_select_one_cross)



#' @examples
#' dico <- kobo_dico( xlsformpath = system.file("sample_xlsform.xlsx", package = "kobocruncher") )
#' datalist <- kobo_data(datapath = system.file("data.xlsx", package = "kobocruncher") )
#' 
#' plot_select_one_cross(datalist = datalist,
#'               dico = dico, 
#'               var = "profile.country",
#'               by_var = "profile.occupation",
#'               showcode = TRUE
#'               )
#' ## test if variable are not in the same frame...
#' plot_select_one_cross(datalist = datalist,
#'               dico = dico, 
#'               var = "profile.country",
#'               by_var = "members.sex",
#'               n = 5,
#'               n_by = 5,
#'               showcode = TRUE
#'               )
#' 
plot_select_one_cross <- function(datalist = datalist,
                            dico = dico,
                            var, 
                            by_var , 
                            datasource = NULL,
                            n = NULL,
                            n_by = NULL,
                            showcode = FALSE) {
  
  requireNamespace("ggplot2")
  requireNamespace("dplyr")
  ## Get default data source name
  if (is.null(datasource)) {
    datasource <- as.character(dico[[3]]$form_title)
  }
  
  data <- kobo_frame(datalist = datalist,
                     dico = dico,
                     var = var)
  
  data2 <- kobo_frame(datalist = datalist,
                      dico = dico,
                      var = by_var)
  
  ## get response rate: rr
  rr <- mean(!is.na(data[[var]]))
  rr2 <- mean(!is.na(data2[[by_var]]))
  
  
  nr <- sum(!is.na(data[[var]]))
  nr2 <- sum(!is.na(data2[[by_var]]))
  
  ## Writing report
  # cat("\n")
  # cat(paste("####", label_varname(var)))
  #cat(paste("#### Variable: ", var))
  
  if (is.nan(rr) | is.nan(rr2)) {
    cat(
      paste0(
        "<strong style=\"color:#0072BC;\">The variable from the form called: ",
        var,
        " or ",
        by_var,
        " could not be identified in the dataset</strong>\n\n"
      )
    )
      return(invisible())
    #return(invisible(NULL))
    
  } else if (!(identical(data, data2))) {
    # nothing to do - the variable are not in the same frame
     cat("")
      return(invisible())
     #return(invisible(NULL))
  } else {
    ## Put a condition in case there's no record
    if (rr != 0 & !(is.nan(rr))) {
      if (by_var != "") {
        if (by_var != var) {
          cnts1 <- data |>
            ## keep only the variable we need
            #tidyselect::all_of(c(var, by_var)) |>
            tidyr::drop_na(tidyselect::all_of(c(var, by_var)))

          ## Need to check that there's actually a proper intersection in the response...
          if (nrow(cnts1) == 0) {
            cat(
              paste0(
                "<strong style=\"color:#0072BC;\">There is not intersection between the answers from the variables from the form called: ",
                var,
                " or ",
                by_var,
                " in the dataset</strong>\n\n"
              )
            )
          } else {
              ## Set the value for n if not set up -
              if( is.null(n)) { n1 = nlevels( as.factor(data[[var]]) )} else { n1 = n} 
              ## Set the value for n_by if not set up -
              if( is.null(n_by)) { n_by1 = nlevels( as.factor(data[[by_var]]) )} else { n_by1 = n_by} 
            
             cnts <- cnts1 |> 
              dplyr::group_by(.data[[var]], .data[[by_var]] ) |>
              dplyr::summarise(n = dplyr::n()) |>
              dplyr::mutate(p = n/nr) |>
              # Lump together factor levels into "other"
              dplyr::mutate(
                x = as.character(forcats::fct_lump_n( as.factor(.data[[var]]), 
                                         n = n1,
                                         w = p,
                                         other_level = paste0("Other ",
                                    nlevels( as.factor(data[[var]]))-n1,
                                    " response options automatically lumped")) ),
                y = as.character(forcats::fct_lump_n( as.factor(.data[[by_var]]), 
                                         n = n_by1,
                                         w = p,
                                         other_level = paste0("Other ",
                                    nlevels( as.factor(data[[by_var]]))-n_by1,
                                    " response options automatically lumped")))
              ) |>
              ## let's summarize again after lumping 
              dplyr::group_by(x, y ) |>
              dplyr::summarise(n = sum(n, na.rm = TRUE)) |>
              dplyr::mutate(p = n/nr) |>
               
              ## Now  counting records per facet..
              dplyr::group_by(y) |>
              dplyr::mutate(cumsum = max(cumsum(as.numeric(n))),
                            pcum = n / cumsum) |>
              ## Relabel
              dplyr::mutate( y0 = label_choiceset(dico = dico, x= by_var)(y) ) |>
              ## Create better label for the facet
              dplyr::mutate( y1 = paste0(y0, " (",cumsum, " records)") )
             
             
          ## Writing code instruction in report
          if (showcode == TRUE) {
            cat( paste0( label_varname(dico = dico, x = var),  "\n",
       "`plot_select_one_cross(datalist, dico, var=\"", var, "\", by_var=\"", by_var, "\",datasource=params$datasource, n=", n1, ",n_by=",n_by1, " )` \n\n "))  }   else {} 
             
            
            ## plot
            require(ggplot2)
            p <- ggplot2::ggplot(cnts, ggplot2::aes(x = pcum,  y = x)) +
              ggplot2::geom_col(fill = "#0072BC") +
              ggplot2::geom_label(
                data =   function(x)  subset(x, pcum < max(pcum) / 1.5),
                ggplot2::aes(label = scales::label_percent(accuracy = .01)(pcum)),
                hjust = -0.1 , vjust = 0.5,
                colour = "black", fill = NA,
                label.size = NA, size = 5 ) +
              ggplot2::geom_label( data =   function(x)subset(x, pcum >= max(pcum) / 1.5),
                ggplot2::aes(label = scales::label_percent(accuracy = .01)(pcum)),
                hjust = 1.1 ,  vjust = 0.5,
                colour = "white", fill = NA,
                label.size = NA,  size = 5  ) +
              ggplot2::scale_x_continuous(labels = scales::label_percent()) +
              ggplot2::facet_wrap(~ y1 , nrow = 3 # ,
                         # labeller = #glue::glue('{
                         #   as_labeller(function(x)
                         #   label_choiceset(dico = dico,
                         #                   x = by_var)(x) ) 
                         # #  } ')
                         ) +
              ggplot2::scale_y_discrete(
                labels = function(x) {
                  label_choiceset(dico = dico,
                                  x = var)(x) |>
                    stringr::str_wrap(40)
                }
              ) +
              ggplot2::coord_cartesian(clip = "off") +
              ggplot2::labs(
                x = NULL,
                y = NULL,
                title = stringr::str_wrap(label_varname(dico = dico, x = var), 90),
                subtitle = stringr::str_wrap(paste0(
                  "Crossed by ", label_varname(dico = dico, x = by_var)
                ), 90),
                caption = glue::glue(
                  "Single choice, Response rate = {scales::label_percent(accuracy = .01)(rr)} on a total of {nrow(data)} records \n Source: {datasource}"
                )
              ) +
              ggplot2::theme_minimal(base_size = 24) +
              ggplot2::geom_vline(xintercept = 0,
                         size = 1.1,
                         colour = "#333333") +
              ggplot2::theme(
                panel.grid.major.x  = ggplot2::element_line(color = "#cbcbcb"),
                panel.grid.major.y  = ggplot2::element_blank(),
                panel.grid.minor = ggplot2::element_blank()
              ) +
              ggplot2::theme(plot.title.position = "plot")
            
            return(p) #  print(p)
          }
        }
      } else {
         cat("")
         #return(invisible(NULL))
         return(invisible())
      }
    } else {
      cat(paste0("<strong style=\"color:#0072BC;\"> No recorded answers for the question: </strong>", var,  "\n\n" ) )
      return(invisible())
    }
    # cat("\n\n")
  }
}




