# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' @title Plotting numeric variable
#' @param datalist An object of the "datalist" class as defined in kobocruncher 
#' @param dico An object of the "kobodico" class format as defined in kobocruncher
#' @param var name of the variable to display
#' @param showcode display the code
#' @export

#' @examples
#' dico <- kobo_dico( xlsformpath = system.file("sample_xlsform.xlsx", package = "kobocruncher") )
#' datalist <- kobo_data(datapath = system.file("data.xlsx", package = "kobocruncher") )
#' 
#' plot_integer(datalist = datalist,
#'               dico = dico, 
#'               var = "members.age",
#'               showcode = TRUE)
plot_integer <- function(datalist = datalist, 
                         dico = dico,
                         var, 
                         showcode = FALSE) {
  
  require("ggplot2") 
  datasource <- as.character(  dico[3][[1]]$form_title ) 
  data <- kobo_frame(datalist = datalist,
                   dico = dico,
                   var = var  )
  ## Cast just in case...
  data[[var]] <- as.integer(data[[var]])
  ## get response rate: rr
  rr <- mean(!is.na(data[[var]]))
  # cat("---\n")
  # cat("\n\n")
 if ( is.nan(rr)) {
    cat("<strong style=\"color:#0072BC;\">This variable could not be identified in the dataset</strong>\n\n")
  } else {
  
  ## Writing report
  if (rr != 0 & ! (is.nan(rr))  ) { 
      ## Writing code instruction in report
      if( showcode == TRUE) {
        cat(paste0(label_varname(dico = dico,
                                                   x = var), "\n",
                                      fontawesome::fa("far fa-copy", fill ="grey"),"  `plot_integer(datalist = datalist, dico = dico, \"", var, "\")` \n\n "))}    else {}
    
    p <- ggplot(data) + 
      geom_histogram(aes( x= .data[[var]]), 
                    # bins = nclass.FD(na.omit(data[[var]])),
                     fill = "#0072BC", 
                     color = "white" 
      ) +
      # scale_y_continuous(labels = scales::label_percent()) +
      labs(x = NULL, y = NULL,
           title = stringr::str_wrap(label_varname(dico = dico, 
                                         x = var), 60), 
           subtitle = if (!is.na(label_varhint(dico = dico, 
                                                         x = var))){ 
                     stringr::str_wrap(label_varhint(dico = dico, 
                                                   x = var), 70)} else { ""},
           caption = glue::glue("Numeric response, Response rate = {scales::label_percent(accuracy = .01)(rr)} on a total of {nrow(data)} records \n Source: {datasource}")) +
  
      theme_minimal( base_size = 13) +
      geom_hline(yintercept = 0, size = 1.1, colour = "#333333") +
      theme( panel.grid.major.y  = element_line(color = "#cbcbcb"), 
           panel.grid.major.x  = element_blank(), 
           panel.grid.minor = element_blank()    ) +
           theme(plot.title.position = "plot")
    
    print(p)
    
    } else { cat("<strong style=\"color:#0072BC;\">No recorded answers for this specific question!</strong>\n\n")}
  # cat("\n\n")
  }
}


#' @title Plotting Select multiple variable
#' @description
#' Note that if the column order is set in the xlsform choice part, the variable will be de factor considered as ordinal and the default ordering will not be done based on frequency
#' @param datalist An object of the "datalist" class as defined in kobocruncher 
#' @param dico An object of the "kobodico" class format as defined in kobocruncher
#' @param var name of the variable to display
#' @param showcode display the code
#' @export

#' @examples
#' dico <- kobo_dico( xlsformpath = system.file("sample_xlsform.xlsx", package = "kobocruncher") )
#' datalist <- kobo_data(datapath = system.file("data.xlsx", package = "kobocruncher") )
#' 
#' 
#' plot_select_multiple(datalist = datalist,
#'               dico = dico, 
#'               var = "profile.reason",
#'               showcode = TRUE
#'             )
#' 
#' plot_select_multiple(datalist = datalist,
#'               dico = dico, 
#'               var = "profile.reason1",
#'               showcode = TRUE
#'             )
#' 
plot_select_multiple <- function(datalist = datalist, 
                                 dico = dico,
                                 var, 
                                 showcode = FALSE) {
  
  require("ggplot2")
  datasource <- as.character(  dico[3][[1]]$form_title ) 
  data <- kobo_frame(datalist = datalist,
                   dico = dico,
                   var = var  )
  
  ## get response rate: rr
  rr <- mean(!is.na(data[[var]]))
  nr <- sum(!is.na(data[[var]]))

  
  if ( is.nan(rr)) {
    cat("<strong style=\"color:#0072BC;\">This variable could not be identified in the dataset</strong>\n\n")
  } else {
  
  ## If not empty
  if (rr != 0 & ! (is.nan(rr)) ) {    
  
  cnts <- data |>
    tidyr::drop_na(tidyselect::all_of(var)) |>
    tidyr::separate_rows(.data[[var]], sep = " ") |>
    ## Check if we have _id -  
    
    # Lump together factor levels into "other"
    dplyr::distinct(`X_id`, !!var := forcats::fct_lump_n(factor(.data[[var]]), n = 5)) |>
    dplyr::count(x := .data[[var]]) |>
    dplyr::mutate(p = n/nr)
  
  ## Manage situation if ordinal variable (i.e. order is set in choices)
  if (any(!is.na(dplyr::filter(dico[[2]], list_name == var)$order))) {
    cnts <- cnts |>
      dplyr::mutate(x = forcats::fct_reorder(x, order, as.numeric))
  } else {
    cnts <- cnts |>
      dplyr::mutate(x = forcats::fct_reorder(x, n))
  }

    
    ## Writing code instruction in report
    if( showcode == TRUE) {
      cat(paste0(label_varname(dico = dico,
                                                   x = var), "\n",
                                      fontawesome::fa("far fa-copy", fill ="grey"),"  `plot_select_multiple(datalist = datalist, dico = dico, \"", var, "\")` \n\n "))}   else {} 
    
    ## Plot
     p <- ggplot(cnts, aes(p, x)) +
      geom_col(fill = "#0072BC") +
      #geom_label(aes(label = scales::label_percent(accuracy = .01)(p))) + 
      ## Position label differently in the bar in white - outside bar in black
      geom_label( data =   function(x) subset(x, p < max(p) / 1.5),
                    aes(label = scales::label_percent(accuracy = .01)(p)),
                    hjust = -0.1 ,
                    vjust = 0.5, 
                    colour = "black", 
                    fill = NA, 
                    label.size = NA, 
                     
                    size = 4   ) +  
      geom_label( data =   function(x) subset(x, p >= max(p) / 1.5),
                    aes(label = scales::label_percent(accuracy = .01)(p)),
                    hjust = 1.1 ,
                    vjust = 0.5, 
                    colour = "white", 
                    fill = NA, 
                    label.size = NA, 
                     
                    size = 4   ) +   
      
      scale_x_continuous(labels = scales::label_percent()) +
      scale_y_discrete(labels = function(x) {label_choiceset(dico = dico,
                                                        x = var)(x) |>
          stringr::str_wrap(40)}) +
      coord_cartesian(clip = "off") +
      labs(x = NULL, y = NULL,
           title = stringr::str_wrap(label_varname(dico = dico,
                                                         x= var), 60),
           subtitle = if (!is.na(label_varhint(dico = dico,
                                                        x = var))){ 
                     stringr::str_wrap(label_varhint(dico = dico,
                                                          x = var), 70)} else { ""},
           caption = glue::glue("Multiple choice question, Response rate = {scales::label_percent(accuracy = .01)(rr)} on a total of {nrow(data)} records \n Source: {datasource}")) +
      theme_minimal( base_size = 15) + 
      geom_vline(xintercept = 0, size = 1.1, colour = "#333333") +
      theme( panel.grid.major.x  = element_line(color = "#cbcbcb"), 
             panel.grid.major.y  = element_blank(), 
             panel.grid.minor = element_blank()    ) +
      theme(plot.title.position = "plot")
     
     
    print(p)
    
    #plot_select_multiple_cross(var,   by_var)
    
  } else { cat("<strong style=\"color:#0072BC;\">No recorded answers for this specific question!</strong> \n\n")}
  # cat("\n\n")
    
  }  
}


#' @title Plotting Select one variable
#' @description Note that if the column order is set in the xlsform choice part, the variable will be de factor considered as ordinal and the default ordering will not be done based on frequency
#' @param datalist An object of the "datalist" class as defined in kobocruncher 
#' @param dico An object of the "kobodico" class format as defined in kobocruncher
#' @param var name of the variable to display
#' @param showcode display the code
#' @export

#' @examples
#' dico <- kobo_dico( xlsformpath = system.file("sample_xlsform.xlsx", package = "kobocruncher") )
#' datalist <- kobo_data(datapath = system.file("data.xlsx", package = "kobocruncher") )
#' 
#' plot_select_one(datalist = datalist,
#'               dico = dico, 
#'               var = "profile.country",
#'               showcode = TRUE)
#' 
#' plot_select_one(datalist = datalist,
#'               dico = dico, 
#'               var = "profile.countryerror",
#'               showcode = TRUE)
plot_select_one <- function(datalist  ,
                            dico  ,
                            var,
                            showcode = FALSE) {

  require("ggplot2")
  ## Get default data source name 
  datasource <- as.character(  dico[3][[1]]$form_title ) 
 
  data <- kobo_frame(datalist = datalist,
                   dico = dico,
                   var = var  )
  
  ## get response rate: rr
  rr <- mean(!is.na(data[[var]]))
  
  if ( is.nan(rr)) {
    cat("<strong style=\"color:#0072BC;\">This variable could not be identified in the dataset</strong>\n\n")
  } else {
  
  ## Put a condition in case there's no record
  if (rr != 0  & ! (is.nan(rr)) ) {
  
  cnts <- data |>
    tidyr::drop_na(tidyselect::all_of(var)) |>
    # Lump together factor levels into "other"
    dplyr::count(x := forcats::fct_lump_n(factor(.data[[var]]), n = 5)) |>
    dplyr::mutate(p = n/sum(n))
  
  
  listvar <- as.data.frame(dico[[1]]) |>
             dplyr::filter( name ==var ) |>
             dplyr::pull(list_name)
  
  ## Manage situation if ordinal variable (i.e. order is set in choices)
  if (any(!is.na(dplyr::filter(dico[[2]], list_name == listvar)$order))) {
    cnts <- cnts |>
      dplyr::mutate(x = forcats::fct_reorder(x, order, as.numeric))
  } else {
    cnts <- cnts |>
      dplyr::mutate(x = forcats::fct_reorder(x, n))
  }
  
  ## Writing code instruction in report
  if( showcode == TRUE) { cat(paste0( label_varname(dico = dico,
                                                   x = var), "\n",
                                      fontawesome::fa("far fa-copy", fill ="grey"),
                                      "`plot_select_one(datalist = datalist, dico = dico, \"", var, "\")` \n\n "))}  else {}
  
    
    ## plot
    require(ggplot2)
    p <- ggplot(cnts, aes(p, x)) +
      geom_col(fill = "#0072BC") +
      
      #geom_label(aes(label = scales::label_percent(accuracy = .01)(p))) +
      ## Position label differently in the bar in white - outside bar in black
      geom_label( data =   function(x) subset(x, p < max(p) / 1.5),
                  aes(label = scales::label_percent(accuracy = .01)(p)),
                  hjust = -0.1 ,
                  vjust = 0.5,
                  colour = "black",
                  fill = NA,
                  label.size = NA,
                  
                  size = 4   ) +
      geom_label( data =   function(x) subset(x, p >= max(p) / 1.5),
                  aes(label = scales::label_percent(accuracy = .01)(p)),
                  hjust = 1.1 ,
                  vjust = 0.5,
                  colour = "white",
                  fill = NA,
                  label.size = NA,
                  
                  size = 4   ) +
      scale_x_continuous(labels = scales::label_percent()) +
      scale_y_discrete(labels = function(x) {label_choiceset(dico = dico, x = var)(x) |>
                      stringr::str_wrap(40)}) +
      coord_cartesian(clip = "off") +
      labs(x = NULL, y = NULL,
           title = stringr::str_wrap(label_varname(dico = dico,
                                                   x = var), 60),
           subtitle = if (!is.na(label_varhint(dico = dico,
                                               x= var))){
             stringr::str_wrap(label_varhint(dico = dico,
                                             x= var), 70)} else { ""},
           caption = glue::glue("Single choice question, Response rate = {scales::label_percent(accuracy = .01)(rr)} on a total of {nrow(data)} records. \n Source: {datasource}")) +
      theme_minimal( base_size = 15) +
      geom_vline(xintercept = 0, size = 1.1, colour = "#333333") +
      theme( panel.grid.major.x  = element_line(color = "#cbcbcb"),
             panel.grid.major.y  = element_blank(),
             panel.grid.minor = element_blank()    ) +
      theme(plot.title.position = "plot")
    
    print(p)
    
  } else { cat("<strong style=\"color:#0072BC;\"> No recorded answers for this specific question!</strong>\n\n")}
  # cat("\n\n")
  }
}  


#' @title Plotting Open Text variables
#' @param datalist An object of the "datalist" class as defined in kobocruncher 
#' @param dico An object of the "kobodico" class format as defined in kobocruncher
#' @param var name of the variable to display
#' @param showcode display the code
#' @export

#' @examples
#' dico <- kobo_dico( xlsformpath = system.file("sample_xlsform.xlsx", package = "kobocruncher") )
#' datalist <- kobo_data(datapath = system.file("data.xlsx", package = "kobocruncher") )
#' 
#' plot_text(datalist = datalist,
#'               dico = dico, 
#'               var = "profile.occupation",
#'               showcode = TRUE)
plot_text <- function(datalist = datalist, 
                      dico = dico,
                      var, 
                      showcode = FALSE) {
  
  datasource <- as.character(  dico[3][[1]]$form_title ) 
  data <- kobo_frame(datalist = datalist,
                   dico = dico,
                   var = var  )
  # cat("---\n")
  # cat("\n\n")
  #cat( stringr::str_wrap(  paste0(  label_varname(var), " (Open Text question)"), 70) )
  # cat(paste("####", label_varname(var)))
  # cat("\n\n")
  #cat("Open Text question\n\n")
  
  rr <- mean(!is.na(data[[var]]))
   if ( is.nan(rr)) {
    cat("<strong style=\"color:#0072BC;\">This variable could not be identified in the dataset</strong>\n\n")
  } else { 
      
  require("tm")
  #Replacing “/”, “@” and “|” with space:
  toSpace <- tm::content_transformer(function (x , pattern ) gsub(pattern, " ", x))  
  # Cleaning the text  #### 
  docs <-  tm::Corpus(tm::VectorSource(data[[var]]))  %>%
            #Text transformation to replace special characters from the text.
            tm::tm_map(., toSpace, "/")  %>%
            tm::tm_map(., toSpace, "@")  %>%
            tm::tm_map(., toSpace, "\\|")  %>%
            # Convert the text to lower case
            tm::tm_map(., content_transformer(tolower))  %>%
            # Remove numbers
            tm::tm_map(., removeNumbers)  %>%
            # Remove punctuations
            tm::tm_map(.,  removePunctuation)  %>%
            # Eliminate extra white spaces
            tm::tm_map(.,  stripWhitespace)  %>%
            # Text stemming - reduces words to their root form.
            tm::tm_map(.,  stemDocument)  %>%
            # Remove common stopwords depending on language
            # The information value of ‘stopwords’ is near zero due to the fact that they 
            # are so common in a language. Removing this kind of words is useful before
            # further analyses. 
            tm::tm_map(., removeWords, stopwords("english"))  %>%
            # Remove your own stop word
            tm::tm_map(., removeWords, c("blabla1", "blabla2")) 
  
    # Step 4 : Build a term-document matrix ####
    # Table containing the frequency of the words. Column names are words and row names are documents. 
    dtm <- tm::TermDocumentMatrix(docs)
    m <- as.matrix(dtm)
    v <- sort(rowSums(m),decreasing=TRUE)
    d <- data.frame(word = names(v),freq=v)
    #head(d, 10)
  
    ## Put a condition in case there's no record
    if(nrow(d) > 0 ) {
      
        ## Writing code instruction in report
        if( showcode == TRUE) {
          cat(paste0(label_varname(dico = dico,
                                                   x = var), "\n",
                                      fontawesome::fa("far fa-copy", fill ="grey"),"  `plot_text(datalist = datalist, dico = dico, \"", var, "\")`  \n\n"))}   else {}
      
      # Step 5 : Generate the Word cloud  ####
      #The importance of words can be illustrated as a word cloud as follow :
      set.seed(1234)
      wordcloud::wordcloud(words = d$word, # words : the words to be plotted
                                freq = d$freq,  # freq : their frequencies
                                min.freq = 1,  # min.freq : words with frequency below min.freq will not be plotted
                                max.words=200, # max.words : maximum number of words to be plotted
                                random.order=FALSE, # random.order : plot words in random order. If false, they will be plotted in decreasing frequency
                                rot.per=0.25,   # rot.per : proportion words with 90 degree rotation (vertical text)
                                colors= RColorBrewer::brewer.pal(8, "Dark2")) # colors : color words from least to most frequent. Use, for example, colors =“black” for single color.
    title( main = stringr::str_wrap( label_varname(dico = dico, 
                                                  x= var), 70),
           sub = glue::glue("Open Text question \n Source: {datasource}" ))  
    
         
      # p1 <- ggplot(d, 
      #              aes(label = word,
      #                  size = freq,
      #                  color = freq )) +
      #       ggwordcloud::geom_text_wordcloud(area_corr = TRUE,
      #                                        rm_outside = TRUE,
      #                                        eccentricity = 1) +
      #       scale_size_area(max_size = 50) +
      #       # scale_radius(range = c(0, 10),  limits = c(0, NA)) +
      #       scale_color_gradient(low = "darkred", high = "red") +
      #       labs(x = NULL, y = NULL,
      #        title = str_wrap(survey_label(var), 60), 
      #        subtitle = if (!is.na(label_varhint(var))){ 
      #          stringr::str_wrap(label_varhint(var), 70)} else { ""},
      #        caption = glue::glue("Wordcloud displaying an Open Text question, Response rate = {scales::label_percent(accuracy = .01)(rr)} on a total of {nrow(data)} records")) +
      #   
      #       theme_minimal( base_size = 13)  
      # print(p1)
      
    
  } else { cat("<strong style=\"color:#0072BC;\">No significant text for this specific question!</strong>\n\n")}
  
  # cat("\n\n")
  }
}

