# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' @title Plotting Correlation
#' 
#' @description blbla
#' 
#' @param datalist An object of the "datalist" class as defined in kobocruncher 
#' @param dico An object of the "kobodico" class format as defined in kobocruncher
#' @param var name of the variable to display
#' @param by_var variable to use for cross tabulation
#' @param showcode display the code
#' @export

#' @examples
#' dico <- kobo_dico( xlsformpath = system.file("sample_xlsform.xlsx", package = "kobocruncher") )
#' datalist <- kobo_data(datapath = system.file("data.xlsx", package = "kobocruncher") )
#' 
#' plot_correlation(datalist = datalist,
#'               dico = dico, 
#'               var = "profile.occupation")
plot_correlation <- function(datalist = datalist, 
                      dico = dico,
                      var, 
                      by_var, 
                      showcode = FALSE) {
  
   # ### Testing number of levels for the 2 variables as 'x' and 'y' must have at least 2 levels
   # if ( by_var != var &
   #      (nlevels(as.factor(as.character(formula$target))) > 1 ) &
   #      (nlevels(as.factor(as.character(formula$tested))) > 1 ) &
   #                     
   #      ## If too many levels, the corrogram is not legible...
   #      (nlevels(as.factor(as.character(formula$target))) < 8 ) &
   #      (nlevels(as.factor(as.character(formula$tested))) < 8 ) &
   #      ## May have class with zero value...
   #      n.class == n.class.notnull
   #                     
   #                )
   #                { p.value  <- round(stats::chisq.test(formula$target,formula$tested)$p.value,4)
   #                } else {            }
   #              
   #              ## Subsetting results on test where p-value is below 0.05
   #              chiquare.true <- chiquare.resultall[ chiquare.resultall$p.value <= 0.05, ]
   #              
   #              ### Case there not any positive test
   #              if (p.value <= 0.05 ) {
   #                cat("No significant association found for this question...\n")
   #              } else {
   #                ## now generating correlation plot for each of the dependent.
   # 
   #                 p <-   corrplot::corrplot(stats::chisq.test(
   #                   MainDataFrame$monit.FamiliyLeft,
   #                   MainDataFrame$monit.RouteIncident)$residuals,
   #                is.cor = FALSE, # use for general matrix to convert to Sq form
   #                cl.pos = "n", ## Do not display the color legend
   #                cl.cex = 0.7, # Size of all label
   #                tl.cex = 0.7, # Size of axis label
   #                tl.srt = 45, # string rotation in degrees
   #                tl.col = "black", # color of text label.
   #                addCoef.col = "grey", # add coeff in the chart
   #                number.cex = 3/ncol(stats::chisq.test(MainDataFrame$monit.FamiliyLeft,MainDataFrame$monit.RouteIncident)), # size of coeff
   #                mar = c(0.5,0.5,4, 0.5), ## margin of plots
   #                title = paste0("Correlation between ", , " & ", )) 
   #                 
   #                 print(p)
   # 
   #              }
}

