# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' @title Output Header
#' 
#' @description Function to add headings within the crunching report - 
#' Headings are by defaults the groups defined in the xlsform - 
#' but can be replaced within the analysis plan by chapter and subchapter
#' 
#' @param dico path to the xlsform file used to colllect the data
#' @param var name of the variable to display
#' @export

#' @examples
#' dico <- kobo_dico( xlsformpath = system.file("sample_xlsform.xlsx", package = "kobocruncher") )
#' 
#' plot_header( dico = dico, 
#'               var = "profile")
plot_header <- function(dico = dico,
                            var) {
  
  requireNamespace("dplyr")
  ## getting header levels
  lvl <- stringr::str_count(var, "\\.")
  
  label <- as.data.frame(dico[1]) |>
           dplyr::filter(name == var) |>
          ## Filter down in case the same var name was given to end group or repat... 
           dplyr::filter(! (type %in% c("end_group", "end_repeat")) ) |>
           dplyr::pull(label)

  ## In case the header comes from chapter   
  lbchap <- as.data.frame(dico[4]) |>
            dplyr::filter(name == var) |>
            dplyr::pull(label)

  if(identical(label, character(0)) ) 
    {title <- glue::glue("{lbchap}") } else {
      if(is.na(label)) { title <- glue::glue("({var})") } else 
      { title <- label} 
   } 
  
  # Join multiple strings into a single string.
  hdr <- stringr::str_c(strrep("#", 1+lvl), " ", title, sep = "")
  
  ## Now Printing the headers
  cat("---\n")
  cat("\n\n")
  cat("\n")
  cat(hdr)
  cat("\n\n")
}

