# WARNING - Generated by {fusen} from /dev/ShinyApp.Rmd: do not edit by hand

#' @title Shiny App - app_kobocruncher
#' 
#' @description  starts the graphical user interface developed with \emph{shiny}.
#' 
#' @param ... A list of Options to be added to the app
#'
#' @importFrom shiny shinyApp
#' @importFrom golem with_golem_options
#' @export
#' @examples
#' 
#' # app_kobocruncher(theme="flatly")
run_app <- function(...) {
  with_golem_options(
    app = shinyApp(ui = app_ui, server = app_server),
    golem_opts = list(...)
  )
}

