# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' Convert to UNHCR branded Powerpoint presentation
#'
#' Format for converting from R Markdown to an UNHCR branded Powerpoint presentation
#'
#' @rdname template_interpretation
#'
#' @param ... extra parameters to pass to `officedown::rpptx_document`
#' @return A powerpoint report
#'
#' @export

template_interpretation <- function(...) {

  pptx_template <- pkg_resource("templates/pptx_template.pptx")

  officedown::rpptx_document(
    reference_doc = pptx_template,
    ...
  )
}
