# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' Initial Template for Automatic Data Exploration
#' The first RMD template gives an output in HTML for easy navigation - the left menu provides smooth transition.
#' It includes a function to automatically run throughout all the survey content. During this stage, data cleaning and new variable creation can be performed through iterations
#'  This report also includes each plot syntax so that they can be easyly pasted for the second report
#' @importFrom unhcrdesign use_unhcr_bslib
#' @rdname template_exploration
#'
#' @param ... extra parameters to pass to `rmarkdown::html_document`
#' 
#' @return An html report
#'
#' @export

template_exploration <- function(...) {
  
  unhcr_theme <- unhcrdesign::use_unhcr_bslib()
  
  rmarkdown::html_document( theme = unhcr_theme,
                            ...)
}

