# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' Report Template 3 for Dissemination and Data Story Telling Template
#' The last template can be used to take note of the data interpretation session. 
#' It will generate a PDF or an paginated HTML page
#' @param back_html Back-cover HTML including contact information
#' @param other_css Add extra css
#' @param number_sections Number section headings
#' @param ... Arguments passed to pagedown::html_paged
#' 
#' @return A pagedown report
#' @export

template_3_dissemination <- function(back_html = TRUE,
                         other_css = NULL,
                         number_sections = FALSE,
                         ...) {
  # base css files
  base_css <- unhcrdesign::use_unhcr_css(c("reset", "color_variables", "fonts"))
  
  # logo css file
  logo_var <- paste0("  --unhcr-logoblue: url(\"", unhcrdesign::use_unhcr_logo(logo = "blue", data_uri = TRUE), "\");")
  logo_css <- tempfile(fileext = ".css")
  writeLines(c(":root {", logo_var, "}"), con = logo_css)

  file.append(base_css, logo_css)

  # specific css files
  paged_base_css <- system.file("css/paged_base.css", package = "kobocruncher")
  paged_simple_css <- system.file("css/paged_simple.css", package = "kobocruncher")

  # html back-cover
  if (back_html) {
    back_html <- system.file("html/back_paged_simple.html", package = "kobocruncher")
  } else {
    back_html <- NULL
  }
  # template
  pagedown::html_paged(
    css = c(base_css, paged_base_css,
            paged_simple_css, other_css),
    includes = list(after_body = back_html),
    number_sections = number_sections,
    ...)
}


