# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' Convert to UNHCR branded HTML website
#'
#' Format for converting from R Markdown to an UNHCR branded HTML website
#'
#' @importFrom unhcrdesign use_unhcr_bslib
#' @rdname template_exploration
#'
#' @param ... extra parameters to pass to `rmarkdown::html_document`
#' @return An html report
#'
#' @export

template_exploration <- function(...) {
  
  unhcr_theme <- unhcrdesign::use_unhcr_bslib()
  
  rmarkdown::html_document( theme = unhcr_theme,
                            ...)
}

