# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand

#' Second Template to prepare a presentation for the Joint Data Interpretation Session
#' 
#' See a more detailed presentation of that step here: https://www.youtube.com/watch?v=0jE-Y7g88K4&feature=youtu.be&t=2305  
#'#'
#' @param ... extra parameters to pass to `officedown::rpptx_document`#' 
#' @return A powerpoint report
#'
#' @export

template_2_interpretation <- function(...) {
 # locations of resource files in the package
  pptx_template <- system.file("templates/pptx_template.pptx", package = "kobocruncher")
  officedown::rpptx_document(  reference_doc = pptx_template,  ...  )
}
