# WARNING - Generated by {fusen} from /dev/flat_dev.Rmd: do not edit by hand


#' Initial Template for Automatic Data Exploration
#' 
#' This template is designed for initial data crunching - The first RMD template gives an output in HTML for easy navigation - the left menu provides smooth transition.
#' It includes a function to automatically run throughout all the survey content. During this stage, data cleaning and new variable creation can be performed through iterations
#' This report also includes each plot syntax so that they can be easily pasted for the second report 
#' 
# usethis::use_rmarkdown_template(
#   template_name = "template_1_exploration",
#   template_dir = NULL,
#   template_description = "Automatic Data Exploration - html",
#   template_create_dir = TRUE
# ) 
#' 
#' @param   datafolder  "data-raw" This is the default folder where to put you data in
#' @param   ridl "ridlproject" Name of the ridl project where you data is documented and archived
#' @param   data "data.xlsx" Name of the data file
#' @param   form "form.xlsx" Name of the xlsform - 
#' @param   datasource "Study name reference" ## String used in caption for all your charts
#' @param   publish "no" Put to "yes" in order to add your report, source and analysis plan as ressource within the same ridl c
#' @param   republish "no"
#' @param   visibility "public"
#' @param   stage "exploration_initial" You may change this to exploration_advanced if you configuring many 
#' @param   language "" Check what you have in your xlsform - ::english (en) -or ::french (fr) or ::spanish (es)
#' @param folder folder within your project where to put the generated report. 
#' Folder will be created if it does not exist
#' 
#' @importFrom unhcrdown html_page pptx_slides paged_simple
#' @importFrom rmarkdown render
#' @importFrom here here
#' 
#' @return nothing the file for the report is generated
#' 
#' @export 
#'
#' @examples
#' # template_1_exploration(datafolder= "data-raw",
#' #                                    ridl =  "ridlproject",
#' #                                     data = "data.xlsx" ,
#' #                                     form =  "form.xlsx",
#' #                                     datasource = "Study name reference",
#' #                                     publish =  "no", 
#' #                                     republish = "no",
#' #                                     visibility = "public",
#' #                                     stage = "exploration_initial",
#' #                                    language = "",
#' #                                    folder = "Report")
template_1_exploration <- function(datafolder= "data-raw",
                                   ridl =  "ridlproject",
                                    data = "data.xlsx" ,
                                    form =  "form.xlsx",
                                    datasource = "Study name reference",
                                    publish =  "no", 
                                    republish = "no",
                                    visibility = "public",
                                    stage = "exploration_initial",
                                   language = "",
                                   folder = "Report"){
  
  
  ## Create the outfolder if it does not exist
  output_dir <- paste0(getwd(),"/",folder)
  if (!dir.exists(output_dir)) {dir.create(output_dir)}
  
  
  rmarkdown::render(
    system.file("rmarkdown/templates/template_A_exploration/skeleton/skeleton.Rmd", package = "kobocruncher"),
    output_file = here::here(folder, paste0('StatFactsheetCtr-', country_asylum_iso3c, '-', year, '.html') ),
    params = list(datafolder= datafolder,
                  ridl =  ridl,
                  data = data  ,
                  form =   form,
                  datasource = datasource,
                  publish =  publish, 
                  republish = publish,
                  visibility= visibility,
                  stage = stage,
                  language =language )  )
}
  
