---
title: "Survey Data Analysis with Kobocruncher"
subtitle: "Session 5 - Searching for Association"
author: "Edouard Legoupil"
institute: "Snr Data Analysis Officer"
date: "`r format(Sys.Date(),  '%d %B %Y')`"
output:
  unhcrdown::html_slides:
    self_contained: true
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  fig.showtext = TRUE
)
library(tidyverse)
library(unhcrthemes)
library(fontawesome)
```


## Significant associations & Chi-square 

---

## How to interpret correlation tables? 



Correlation tables only appear if the question has a significant relationship with another indicator. All the answer options for the two questions are seen in the rows and columns and each cell conveys the relationship between the two answer options. Each cell value indicates two characteristics of the relationship: the strength (numeric value) and the direction (- or + sign). The larger the numeric value, the stronger the relationship. Pay attention to the stronger relationships in a table. A + sign indicates same direction (one answer occurs more frequently with the other answer that forms the cell). A – sign indicates opposite direction (one answer occurs less frequently with the other answer). For easier interpretation, focus only on + correlations.



In this example the strongest relationships are identified by the bigger numbers and circles. Choose the strongest or most relevant positive (+) relationship to ease the interpretation. For this table, the following interpretation can be made: “When a person reports that they have witnessed or suffered any incidents (Row ‘Yes’), they are more likely to report that they feel lonely or socially isolated in their current location (Column ‘Strongly Agree’).



---
class: inverse, center, middle

# TIME TO PRACTISE ON YOUR OWN 

5 minutes! 

 - Download again locally and fill in the correlation
 
 - upload and knit again your report
 
 
 
---
class: inverse, center, middle

# Thank you


__Next session__:  [06-Cleaning_and_Indicator_calculation](06-Cleaning_and_Indicator_calculation.html) after reviewing the first iteration of the reports, we can identify potential data quality issue to fix and create calculated variable and indicator 
